#define DOWNLOAD "download"
#define UPLOAD "upload"
#define END_MARK "\r\n"
#define DEFAULT_MARK  'n'
#define DOWNLOAD_MARK 'd'
#define UPLOAD_MARK   'u'
#define FILESIZE_MARK 'f'
#define FILENAME_MARK 'k'
#define ENDF_MARK     'b'
#define MAX_BUFF      8192
