//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define IDI_ARYAN                       1
#define IDC_KEYS                        100
#define IDD_DIALOG1                     101
#define IDC_KEYS2                       101
#define IDR_MENU2                       104
#define IDD_DIALOG2                     110
#define IDD_DIALOG3                     111
#define IDR_MENU1                       114
#define IDB_TREE                        132
#define IDB_FILE                        133
#define IDR_MENU3                       134
#define IDD_FILE                        135
#define IDB_FLOPPY                      139
#define IDB_CD                          141
#define IDB_STATIC                      143
#define IDB_NETWORK                     145
#define IDB_FOLDER                      149
#define IDB_BACK                        153
#define IDR_TOOLBAR1                    172
#define IDR_COMMANDS                    174
#define IDR_MENU4                       175
#define IDR_MENUFolder                  177
#define IDB_BOOKMARK                    179
#define IDR_MENUBOOK                    181
#define IDI_BOOKMARKRED                 192
#define IDI_BOOKMARKBLUE                193
#define IDI_BOOKMARK                    194
#define IDI_BOOKMARKPURPLE              195
#define IDC_TASK_TAB                    200
#define IDI_STATIC                      227
#define IDI_FILE                        233
#define IDI_TEXT                        236
#define IDI_MEDIA                       237
#define IDI_EXE                         243
#define IDI_FOLDER                      246
#define IDI_FLOPPY                      247
#define IDI_CD                          248
#define IDI_NETWORK                     249
#define IDI_PICTURE                     250
#define IDI_VIDEO                       251
#define IDI_COMPRESSED                  253
#define IDD_RENAME                      259
#define IDR_DOWNLOAD                    260
#define IDD_KEYLOG                      261
#define IDD_CONNECT                     262
#define IDD_SCREEN                      263
#define IDD_SCREEN_ABD                  263
#define IDD_SETTINGS                    264
#define IDR_KEY                         267
#define IDD_SEARCH                      270
#define IDR_MENU5                       271
#define IDD_SERVEREDIT                  272
#define EULA                            273
#define IDD_PASSWORDS                   274
#define IDD_SERVICES                    275
#define IDR_MENU6                       276
#define IDD_REGISTERYMAN                277
#define IDD_SHELLABC                    300
#define IDI_DWORD                       303
#define IDI_STRING                      304
#define IDR_MENU7                       305
#define IDD_INSTALLEDPROGS              306
#define IDR_MENU8                       307
#define IDI_IE                          310
#define IDI_FIREFOX                     314
#define IDI_SERVICE                     318
#define IDI_CONNECTION                  319
#define IDI_MEDIUMPING                  320
#define IDI_HIGHPING                    322
#define IDI_LOWPING                     323
#define IDR_MENU9                       325
#define IDI_FILE_STOP                   329
#define IDI_FILE_PLAY                   330
#define IDI_FILE_PAUSE                  331
#define IDC_FILE_STATUS                 1011
#define IDC_TASK_STATUS                 1012
#define IDC_MAIN_STATUS                 1013
#define IDC_SERVERLIST                  1014
#define IDC_LOGS                        1015
#define IDC_CONNECTIONSTATUS            1017
#define IDC_COMMANDS                    1019
#define IDC_SENDCMD                     1020
#define IDC_SHELL_STATUS                1021
#define IDC_TASKLIST                    1021
#define IDC_Windows                     1022
#define IDC_LISTDIR                     1036
#define IDC_TREE1                       1037
#define IDC_FILELIST                    1038
#define IDC_BOOKMARKS                   1039
#define IDC_FOLDERS                     1041
#define IDC_DOWNLOADS                   1043
#define IDC_TAB1                        1044
#define IDC_NAME                        1057
#define IDC_SETNAME                     1058
#define IDC_MAINPORT                    1066
#define IDC_FILEPORT                    1067
#define IDC_SEARCHLIST                  1082
#define IDC_SEARCH                      1083
#define IDC_DIR                         1084
#define IDC_FILENAME                    1085
#define IDC_IPADDRESS                   1086
#define IDC_SERIVCENAME                 1087
#define IDC_OK                          1088
#define IDC_IP                          1089
#define IDC_BUILD                       1093
#define IDC_AGREE                       1095
#define IDC_DISAGREE                    1096
#define IDC_EULA                        1097
#define IDC_PASSWORDS                   1099
#define IDC_SERVICES                    1100
#define IDC_KEYLIST                     1102
#define IDC_REGFOLDERS                  1103
#define IDC_LIST2                       1106
#define IDC_PROGRESS                    1109
#define IDC_SLIDER1                     1110
#define IDC_TAB2                        1115
#define IDC_PROGRESSA                   1117
#define IDC_CMD1                        1121
#define IDC_PROGS                       1123
#define IDC_OKSETTING                   1129
#define IDC_SETTINGTEXT                 1131
#define IDC_SETTINGTEXT1                1132
#define IDC_SETTINGTEXT2                1133
#define IDC_SETTINGTEXT3                1134
#define IDC_KEYSCOLOUR                  1135
#define IDC_KEYCOLOUR                   1136
#define IDC_KEYSCOLOUR2                 1137
#define IDC_KEYCOLOUR2                  1138
#define IDC_KEYLOGGERCOLOURS            1140
#define IDC_KEYSCOLOUR3                 1141
#define IDC_KEYCOLOUR3                  1142
#define IDC_KEYCOLOUR4                  1143
#define IDC_TAB3                        1146
#define IDC_KEYSCOLOUR4                 1147
#define IDC_TAB4                        1148
#define IDC_STATICA                     1149
#define IDC_STATICB                     1150
#define IDC_ID                          1152
#define IDC_PROGRESS1                   1153
#define IDC_SETTING_MAIN_STATUS         2000
#define IDC_LISTEN                      40001
#define IDC_DISCONNECT                  40002
#define IDC_EXIT                        40003
#define IDC_RESET                       40004
#define IDC_FILEMANAGER                 40005
#define IDC_SHELL                       40006
#define IDC_TASKMANAGER                 40007
#define IDC_CONNECTIONOPTIONS           40008
#define IDC_EDITSERVER                  40009
#define IDC_TASK_KILL                   40011
#define IDC_REFRESH_TASK                40012
#define IDC_FOLDER                      40013
#define IDC_DELETE                      40014
#define IDC_DELETEFILE                  40014
#define IDC_BACK                        40015
#define IDC_FORWARD                     40016
#define ID_BUTTON40017                  40017
#define IDC_LOGOFF                      40018
#define IDC_SHUTDOWN                    40019
#define IDC_RESTART                     40020
#define IDC_BOOKMARK                    40026
#define IDC_ENTERDIR                    40027
#define IDC_DOWNLOAD                    40028
#define IDC_UPLOAD                      40029
#define IDC_GOTO                        40030
#define IDC_COPY                        40033
#define IDC_PASTE                       40034
#define IDC_MOVE                        40037
#define IDC_RENAME                      40038
#define IDC_NEW_FOLDER                  40039
#define IDC_RENAME_FOLDER               40040
#define IDC_SCREENCAPTURE               40042
#define IDC_SETTINGS                    40043
#define IDC_KEYLOGGER                   40044
#define IDC_SETTINGS2                   40044
#define IDC_WINDOWTEXT                  40046
#define IDC_TIME                        40047
#define IDC_TEXTNORMAL                  40048
#define IDC_BACKGROUND                  40049
#define IDC_FIND                        40051
#define IDC_KILL                        40054
#define IDC_EXECUTE                     40055
#define IDC_SEARCH_STATUS               40056
#define IDC_FIREFOX                     40056
#define IDC_SERVICEMANAGER              40057
#define IDC_CMD                         40058
#define IDC_REGISTRY                    40059
#define IDC_GOTOSITE                    40060
#define IDC_COPYPW                      40061
#define IDC_COPYUSER                    40062
#define IDC_DOWNLOAD_URL                40064
#define IDC_REFRESH                     40065
#define IDC_BROADCAST_FILEMAN           40066
#define IDC_BROADCAST_TASKMAN           40067
#define IDC_BROADCAST_SERVICE           40068
#define IDC_BROADCAST_REG               40069
#define IDC_BROADCAST_SCREENCAPTURE     40070
#define IDC_BROADCAST_KEYLOG            40071
#define IDC_BROADCAST_FIREFOX           40072
#define IDC_BROADCAST_CMD               40073
#define IDC_BROADCAST_KILL              40075
#define IDC_LOCK                        40078
#define IDC_BROADCAST_SHUTDOWN          40079
#define IDC_BROADCAST_LOCK              40080
#define IDC_BROADCAST_LOGOFF            40081
#define IDC_APPSMAN                     40082
#define ID_TOOL_MODIFY                  40083
#define IDC_DELETEKEY                   40084
#define IDC_EXECUTE_PROG                40085
#define IDC_REMOVE_PROG                 40086
#define IDC_HELPA                       40087
#define IDC_ABOUT                       40088
#define IDC_WEBCAM                      40089
#define ID_DOWNLOADS_STOP               40090
#define ID_DOWNLOADS_PAUSE              40091
#define ID_DOWNLOADS_RESUME             40092
#define IDC_STOP                        40093
#define IDC_PAUSE                       40094
#define IDC_RESUME                      40095

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         40096
#define _APS_NEXT_CONTROL_VALUE         1154
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
