//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource.rc
//
#define IDR_24                          1
#define IDI_ICON1                       2
#define IDC_MAIN_STATUS                 10
#define IDD_MAIN                        101
#define IDR_COMMANDS                    102
#define IDR_MENU2                       103
#define IDD_CONNECT                     104
#define IDD_FILE                        105
#define IDD_RENAME                      106
#define IDD_SCREENCAPTURE               107
#define IDD_SYSTEMMANAGER               108
#define IDD_WEBCAM                      109
#define IDR_FILE_FILE                   114
#define IDR_WIN                         116
#define IDR_TASK                        117
#define IDR_SERVICES                    118
#define IDR_INSTALLED                   119
#define IDR_FILE_TRANSFER               120
#define IDI_TEXT                        121
#define IDI_DOWN                        122
#define IDI_UP                          123
#define IDI_BACK                        124
#define IDI_CD                          125
#define IDI_DEFAULT                     126
#define IDI_FLOP                        127
#define IDI_SERVER                      128
#define IDI_FOLDER                      129
#define IDI_DRIVE                       131
#define IDI_NETWORK                     132
#define IDI_EXE                         133
#define IDI_FILM                        135
#define IDI_PIC                         136
#define IDD_KEYLOG                      137
#define IDR_OPTIONS                     138
#define IDR_SCREEN                      140
#define IDD_PACKETSNIFF                 141
#define IDR_PORTS                       142
#define IDR_DEFAULT1                    143
#define IDC_SERVERLIST                  1000
#define IDC_INFORMATIOND                1001
#define IDC_TAB3                        1002
#define IDC_DRIVES                      1003
#define IDC_LOGS                        1004
#define IDC_FOLDERLIST                  1004
#define IDC_TRANSFER                    1005
#define IDC_SEARCH                      1006
#define IDC_DIRECTORY                   1007
#define IDC_FILE                        1008
#define IDC_FILETAB                     1009
#define IDC_NAME                        1010
#define IDC_EDIT2                       1011
#define IDC_ID                          1012
#define IDC_WINTEXT                     1013
#define IDC_EDIT1                       1013
#define IDC_SIZEWIN                     1014
#define IDC_SETNAME                     1014
#define IDC_SLIDER1                     1015
#define IDC_FILENAME                    1015
#define IDC_PROGRESS1                   1016
#define IDC_SYSTEMTAB                   1018
#define IDC_PROCESSES                   1019
#define IDC_KEYS                        1021
#define IDC_ONLINE                      1022
#define IDC_SERVICES                    1023
#define IDC_PROGRESSA                   1023
#define IDC_WINDOWS                     1024
#define IDC_OFFLINE                     1024
#define IDC_INSTALLED                   1025
#define IDC_INTERVAL                    1026
#define IDC_SINGLESHOT                  1027
#define IDC_PACKET                      1029
#define IDC_DIR                         1032
#define IDC_GO                          1033
#define IDC_PORTS                       1035
#define IDC_TAB2                        1036
#define IDC_SPIN1                       1037
#define IDC_SYSTEM_MANAGER              40001
#define IDC_FILEMANAGER                 40002
#define IDC_SCREENCAPTURE               40003
#define IDC_WEBCAM                      40004
#define IDC_LISTEN                      40005
#define IDC_DELETE                      40006
#define IDR_REFRESH                     40007
#define IDC_COPY                        40008
#define IDC_PASTE                       40009
#define IDC_DOWNLOAD                    40010
#define IDC_UPLOAD                      40011
#define IDC_STOP                        40012
#define IDC_PAUSE                       40013
#define IDC_START                       40014
#define IDC_REFRESH                     40015
#define IDC_EXECUTE                     40016
#define IDC_KILL                        40017
#define IDC_REFRESHS                    40018
#define IDC_REFRESHP                    40019
#define IDC_REFRESHT                    40020
#define IDC_CLOSE                       40022
#define IDC_NORMAL                      40023
#define IDC_HIDDEN                      40024
#define IDC_TEXTNORMAL                  40025
#define IDC_TIME                        40026
#define IDC_WINDOWTEXT                  40027
#define IDC_BACKGROUND                  40028
#define IDC_KEYLOGGER                   40029
#define IDC_SINGLE                      40030
#define IDC_PACKETSNIFF                 40031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         40032
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
