;
;  This is easy way to get commands list for peopel with bad memory like me ;)
;  this script only works for mIRC.
;  Glow
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


alias commandslist {
  echo -a -[ command list ]-
  echo -a 1. / "commands.list" / "Lists all available commands"
  echo -a 2. / "cvar.list" / "prints a list of all cvars"
  echo -a 3. / "cvar.get" / "gets the content of a cvar"
  echo -a 4. / "cvar.set" / "sets the content of a cvar"
  echo -a 5. / "cvar.loadconfig" / "loads config from a file"
  echo -a 6. / "cvar.saveconfig" / "saves config to a file"
  echo -a 7. / "mac.logout" / "logs the user out"
  echo -a 8. / "***" / "logs the user in"
  echo -a 9. / "bot.about" / "displays the info the author wants you to see"
  echo -a 10. / "bot.die" / "terminates the bot"
  echo -a 11. / "bot.dns" / "resolves ip/hostname by dns"
  echo -a 12. / "bot.execute" / "makes the bot execute a .exe"
  echo -a 13. / "bot.id" / "displays the id of the current code"
  echo -a 14. / "bot.nick" / "changes the nickname of the bot"
  echo -a 15. / "bot.open" / "opens a file (whatever)"
  echo -a 16. / "bot.remove" / "removes the bot"
  echo -a 17. / "bot.removeallbut" / "removes the bot if id does not match"
  echo -a 18. / "bot.rndnick" / "makes the bot generate a new random nick"
  echo -a 19. / "bot.status" / "gives status"
  echo -a 20. / "bot.sysinfo" / "displays the system info"
  echo -a 21. / "bot.longuptime" / "If uptime > 7 days then bot will respond"
  echo -a 22. / "bot.highspeed" / "If speed > 5000 then bot will respond"
  echo -a 23. / "bot.quit" / "quits the bot"
  echo -a 24. / "bot.flushdns" / "flushes the bots dns cache"
  echo -a 25. / "bot.secure" / "delete shares / disable dcom"
  echo -a 26. / "bot.unsecure" / "enable shares / enable dcom"
  echo -a 27. / "bot.command" / "runs a command with system()"
  echo -a 28. / "bot.colors" / "Show you colors :D"
  echo -a 29. / "irc.disconnect" / "disconnects the bot from irc"
  echo -a 30. / "irc.action" / "lets the bot perform an action"
  echo -a 31. / "irc.getedu" / "prints netinfo when the bot is .edu"
  echo -a 32. / "irc.gethost" / "prints netinfo when host matches"
  echo -a 33. / "irc.join" / "makes the bot join a channel"
  echo -a 34. / "irc.mode" / "lets the bot perform a mode change"
  echo -a 35. / "irc.netinfo" / "prints netinfo"
  echo -a 36. / "irc.part" / "makes the bot part a channel"
  echo -a 37. / "irc.privmsg" / "sends a privmsg"
  echo -a 38. / "irc.quit" / "quits the bot"
  echo -a 39. / "irc.raw" / "sends a raw message to the irc server"
  echo -a 40. / "irc.reconnect" / "reconnects to the server"
  echo -a 41. / "irc.server" / "changes the server the bot connects to"
  echo -a 42. / "http.download" / "downloads a file from http"
  echo -a 43. / "http.execute" / "updates the bot from a http url"
  echo -a 44. / "http.update" / "executes a file from a http url"
  echo -a 45. / "http.visit" / "visits an url with a specified referrer"
  echo -a 46. / "ftp.download" / "downloads a file from ftp"
  echo -a 47. / "ftp.execute" / "updates the bot from a ftp url"
  echo -a 48. / "ftp.update" / "executes a file from a ftp url"
  echo -a 49. / "http.speedtest" / "Speed Test to see how fast the bot."
  echo -a 50. / "ddos.udpflood" / "starts a UDP flood"
  echo -a 51. / "ddos.synflood" / "starts an SYN flood"
  echo -a 52. / "ddos.httpflood" / "starts a HTTP flood"
  echo -a 53. / "ddos.stop" / "stops all floods"
  echo -a 54. / "ddos.phatsyn" / "starts syn flood"
  echo -a 55. / "ddos.phaticmp" / "starts icmp flood"
  echo -a 56. / "ddos.phatwonk" / "starts leet flood"
  echo -a 57. / "redirect.tcp" / "starts a tcp port redirect"
  echo -a 58. / "redirect.gre" / "starts a gre redirect"
  echo -a 59. / "redirect.http" / "starts a http proxy"
  echo -a 60. / "redirect.https" / "starts a https proxy"
  echo -a 61. / "redirect.socks" / "starts a socks4 proxy"
  echo -a 62. / "redirect.socks5" / "starts a socks5 proxy"
  echo -a 63. / "redirect.stop" / "stops all redirects running"
  echo -a 64. / "rsl.reboot" / "reboots the computer"
  echo -a 65. / "rsl.shutdown" / "shuts the computer down"
  echo -a 66. / "rsl.logoff" / "logs the user off"
  echo -a 67. / "pctrl.list" / "lists all processes"
  echo -a 68. / "pctrl.kill" / "kills a process"
  echo -a 69. / "pctrl.listsvc" / "lists all services"
  echo -a 70. / "pctrl.killsvc" / "deletes/stops service"
  echo -a 71. / "pctrl.killpid" / "kills a pid"
  echo -a 72. / "inst.asadd" / "adds an autostart entry"
  echo -a 73. / "inst.asdel" / "deletes an autostart entry"
  echo -a 74. / "inst.svcadd" / "adds a service to scm"
  echo -a 75. / "inst.svcdel" / "deletes a service from scm"
  echo -a 76. / "harvest.cdkeys" / "makes the bot get a list of cdkeys"
  echo -a 77. / "harvest.emails" / "makes the bot get a list of emails"
  echo -a 78. / "harvest.emailshttp" / "makes the bot get a list of emails via http"
  echo -a 79. / "harvest.aol" / "makes the bot get aol stuff"
  echo -a 80. / "harvest.registry" / "makes the bot get registry info from exact registry path"
  echo -a 81. / "harvest.windowskeys" / "makes the bot get windows registry info"
  echo -a 82. / "logic.ifuptime" / "exec command if uptime is bigger than specified"
  echo -a 83. / "logic.ifspeed" / "exec command if speed(via speedtest) is bigger than specified"
  echo -a 84. / "plugin.load" / "loads a plugin"
  echo -a 85. / "plugin.unload" / "unloads a plugin (not supported yet)"
  echo -a 86. / "shell.handler" / "FallBack handler for shell"
  echo -a 87. / "shell.enable" / "Enable shell handler"
  echo -a 88. / "shell.disable" / "Disable shell handler"
  echo -a 89. / "scan.addnetrange" / "adds a netrange to the scanner"
  echo -a 90. / "scan.delnetrange" / "deletes a netrange from the scanner"
  echo -a 91. / "scan.listnetranges" / "lists all netranges registered with the scanner"
  echo -a 92. / "scan.clearnetranges" / "clears all netranges registered with the scanner"
  echo -a 93. / "scan.resetnetranges" / "resets netranges to the localhost"
  echo -a 94. / "scan.enable" / "enables a scanner module"
  echo -a 95. / "scan.disable" / "disables a scanner module"
  echo -a 96. / "scan.startall" / "enable all Scanners and start scanning"
  echo -a 97. / "scan.stopall" / "disable all Scanners and stop scanning"
  echo -a 98. / "scan.start" / "signal start to child threads"
  echo -a 99. / "scan.stop" / "signal stop to child threads"
}




