"C:\progra~1\kazaa\myshar~1\MSN Hacks.exe""
"C:\progra~1\kazaa\myshar~1\Crash MSN.exe"
"C:\progra~1\kazaa\myshar~1\Hotmail Hacker.exe"
"C:\progra~1\kazaa\myshar~1\CC Generator.ex"
"C:\progra~1\kazaa\myshar~1\Windows XP Key Generator.exe"
"C:\progra~1\kazaa\myshar~1\Lindows Full Version.exe"
"C:\progra~1\kazaa\myshar~1\Asain Anal Porn.exe"
"C:\progra~1\kazaa\myshar~1\Black Anal Porn.exe"
"C:\progra~1\kazaa\myshar~1\White Anal Porn.exe"
"C:\progra~1\kazaa\myshar~1\BRITNEY SPEARS PORN COMPRESSED.exe"
"C:\progra~1\kazaa\myshar~1\1000s OF PORNOGRAPHY COMPRESSED.exe"
"C:\progra~1\kazaa\myshar~1\F1 2002 Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Broadband Uncap.exe"
"C:\progra~1\kazaa\myshar~1\Cable Uncap.exe"
"C:\progra~1\kazaa\myshar~1\Card Properly.exe"
"C:\progra~1\kazaa\myshar~1\AIM Password Stealer.exe"
"C:\progra~1\kazaa\myshar~1\10001 Computer Exploits.exe"
"C:\progra~1\kazaa\myshar~1\Crash other computers (Works on all systems).exe"
"C:\progra~1\kazaa\myshar~1\PROGRAM AND GAME CRACKER (1000s of different types supported).exe"
"C:\progra~1\kazaa\myshar~1\Universal Crack.exe"
"C:\progra~1\kazaa\myshar~1\1001 Game Trainers.exe"
"C:\progra~1\kazaa\myshar~1\Red Hat Linux 7.2 Compressed.exe"
"C:\progra~1\kazaa\myshar~1\SOF2 Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Soldier Of Fortune 2 Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\SpiderMan Game Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\StarWars2 Game Downloader (All 4 Games Included).exe"
"C:\progra~1\kazaa\myshar~1\Valid Credit-Card List (Compressed).exe"
"C:\progra~1\kazaa\myshar~1\Windows 2000 Key Generator (All Versions).exe"
"C:\progra~1\kazaa\myshar~1\Windows 2000 PRO Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Windows Keys List (ALL VERSIONS SUPPORTED).exe"
"C:\progra~1\kazaa\myshar~1\Windows ME Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Windows XP Pro Key Generator(All Versions).exe"
"C:\progra~1\kazaa\myshar~1\Windows XP PRO Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\GTA 3 Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Grand Theft Auto 3 Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Credit-Card Checker.exe"
"C:\progra~1\kazaa\myshar~1\DSL Uncap.exe"
"C:\progra~1\kazaa\myshar~1\Explosives Handbook.exe"
"C:\progra~1\kazaa\myshar~1\Universal Game Crack & Trainer.exe"
"C:\progra~1\kazaa\myshar~1\10 Huge Porn Movies Compressed.exe"
"C:\progra~1\kazaa\myshar~1\Norton AntiVirus 2002 Full.exe"
"C:\progra~1\kazaa\myshar~1\Nero Burning Rom 6.0 FULL.exe"
"C:\progra~1\kazaa\myshar~1\Napster 8.7.exe"
"C:\progra~1\kazaa\myshar~1\Lesbian Porn Sex (Compressed).exe"
"C:\progra~1\kazaa\myshar~1\Learn To Hack Servers.exe"
"C:\progra~1\kazaa\myshar~1\List of Username & Passwords For XXX Sites.exe"
"C:\progra~1\kazaa\myshar~1\McAfee AntiVirus 11.2.exe"
"C:\progra~1\kazaa\myshar~1\Aria Giovanni Fingers Her Pussy (Compressed).exe"
"C:\progra~1\kazaa\myshar~1\Pamela Anderson Masturbation (Compressed).exe"
"C:\progra~1\kazaa\myshar~1\13 year old girl fingers herself (Compressed).exe"
"C:\progra~1\kazaa\myshar~1\Hot Asian Sex (Compressed).exe"
"C:\progra~1\kazaa\myshar~1\Warcraft 4 Full Install Beta.exe"
"C:\progra~1\kazaa\myshar~1\Soldier of Fortune 3 Full Install Beta.exe"
"C:\progra~1\kazaa\myshar~1\Half-Life 2 Full Install Beta.exe"
"C:\progra~1\kazaa\myshar~1\Diablo 2 Valid CDKey Generator.exe"
"C:\progra~1\kazaa\myshar~1\Modem Booster.exe"
"C:\progra~1\kazaa\myshar~1\Doom 3 Full Install Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Doom III Full Install Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Quake 3 Valid CDKey Generator.exe"
"C:\progra~1\kazaa\myshar~1\Quake 3 Full Downloader.exe"
"C:\progra~1\kazaa\myshar~1\Quake 4 Full Install Beta.exe"
"C:\progra~1\kazaa\myshar~1\Counter-Strike Hacks.exe"
"C:\progra~1\kazaa\myshar~1\Hack You School.exe"
"C:\progra~1\kazaa\myshar~1\Zone Flooder.exe"
"C:\progra~1\kazaa\myshar~1\Hotmail Password Cracker.exe"
"C:\progra~1\kazaa\myshar~1\Microsoft Hacker.exe"
"C:\progra~1\kazaa\myshar~1\Half-Life Hacks.exe"
"C:\progra~1\kazaa\myshar~1\Hotmail Account Cracker.exe"
"C:\progra~1\kazaa\myshar~1\Hardcore Porn Sex (Compressed).exe"
"C:\progra~1\kazaa\myshar~1\How To Crash Servers.exe"
"C:\progra~1\kazaa\myshar~1\ICQ Password Cracker.exe"
"C:\progra~1\kazaa\myshar~1\MSN Hacker.exe"
"C:\progra~1\kazaa\myshar~1\Internet Connection Killer.exe"
"C:\progra~1\kazaa\myshar~1\Internet SpeedUp (DialUp & Broadband).exe"
"C:\progra~1\kazaa\myshar~1\Warez Downloader (1000s of files to search).exe"
"C:\progra~1\kazaa\myshar~1\Website Cracker.exe"
"C:\progra~1\kazaa\myshar~1\Windows Hacks.exe"
"C:\progra~1\kazaa\myshar~1\Yahoo Password Stealer.exe"
"C:\progra~1\kazaa\myshar~1\Key Logger.exe"
"C:\progra~1\kazaa\myshar~1\ZoneAlarm FULL Install (Version 6.8).exe"
"C:\progra~1\kazaa\myshar~1\Learn How To Hack.exe"
"C:\progra~1\kazaa\myshar~1\Large Porn Movie (Compressed).exe"
"C:\progra~1\kazaa\myshar~1\Anarchy Book.exe"
"C:\progra~1\kazaa\myshar~1\Virtual Online Chat 5.7.exe"
"C:\progra~1\kazaa\myshar~1\Netbus 4.4.exe"
"C:\progra~1\kazaa\myshar~1\Sub7 8.9.exe"
"C:\progra~1\kazaa\myshar~1\Windows 98 SE Full Install.exe"
"C:\progra~1\kazaa\myshar~1\mIRC Flooder.exe"
"C:\progra~1\kazaa\myshar~1\Homepage Hacker.exe"
"C:\progra~1\kazaa\myshar~1\300 Lesbain Pictures Compressed.exe"
"C:\progra~1\kazaa\myshar~1\kmd30_en.exe"
"C:\progra~1\kazaa\myshar~1\Mobile Phone Hacker.exe"
"C:\progra~1\kazaa\myshar~1\Return To Castle Wolfenstein Valid Key Generator.exe"
"C:\progra~1\kazaa\myshar~1\RTCW Valid Key Generator.exe"
"C:\progra~1\kazaa\myshar~1\Kazaa Queue Skip.exe"
