<?php if(!defined('__INDEX__'))die();
define('LNG_MBOTS','Боты');
define('LNG_MBOTS_FILTER','Фильтр');
define('LNG_MBOTS_FILTER_CIDS','CompID\'s:');
define('LNG_MBOTS_FILTER_BNS','Ботнеты:');
define('LNG_MBOTS_FILTER_CNTS','Страны:');
define('LNG_MBOTS_FILTER_IPS','IP\'s:');
define('LNG_MBOTS_FILTER_TYPE','Тип:');
define('LNG_MBOTS_FILTER_TYPE1','Вне NAT');
define('LNG_MBOTS_FILTER_TYPE2','В NAT');
define('LNG_MBOTS_FILTER_TYPE3','Любой');
define('LNG_MBOTS_FILTER_APPLY','Применить');
define('LNG_MBOTS_RESULT','Результат:');
define('LNG_MBOTS_RESULT_NONE','Пусто');
define('LNG_MBOTS_RESULT_CID','CompID');
define('LNG_MBOTS_RESULT_VERBID','Версия/Ботнет');
define('LNG_MBOTS_RESULT_IP','IP');
define('LNG_MBOTS_RESULT_CNT','Страна');
define('LNG_MBOTS_RESULT_SOCKS','Сокс');
define('LNG_MBOTS_RESULT_PROXY','Прокси');
define('LNG_MBOTS_RESULT_ONLINE','Время&nbsp;в&nbsp;онлайн');
define('LNG_MBOTS_RESULT_LAG','Lag');
define('LNG_MBOTS_RESULT_HIDEIP','Скрыть');
define('LNG_MBOTS_RESULT_LS_SS','Скриншот');
define('LNG_MBOTS_RESULT_LS_KOS','Убить&nbsp;ОС');
define('LNG_MBOTS_RESULT_TIME','Время&nbsp;отчета');
define('LNG_MBOTS_RESULT_FTIME','Время&nbsp;первого&nbsp;отчета');
define('LNG_MBOTS_RESULT_STATUS','Статус:');
define('LNG_MBOTS_RESULT_STATUS_1','Не использован');
define('LNG_MBOTS_RESULT_STATUS_2','Использован');
define('LNG_MBOTS_RESULT_STATUS_3','Пометить как использованый');
define('LNG_MBOTS_RESULT_STATUS_4','Пометить как не использованый');
define('LNG_MBOTS_RESULT_STATUS_KOS_OK','УБИТ');
define('LNG_MBOTS_RESULT_STATUS_KOS_FL','ОШИБКА');
define('LNG_MBOTS_LS_SS_VIEW','Просмотр');
define('LNG_MBOTS_LS_KOS_VIEW','Убить');
define('LNG_MBOTS_RESULT_PREV','<< Назад');
define('LNG_MBOTS_RESULT_NEXT','Далее >>');
define('LNG_MBOTS_SS','Скриншот');
define('LNG_MBOTS_KOS','Убить ОС');
define('LNG_MBOTS_LS_NONE','CompID не найден.');
define('LNG_MBOTS_SOCKS','Сокс');
define('LNG_MBOTS_SOCKS_NONE','CompID не найден.');
define('LNG_MBOTS_SOCKS_SP','IP:Port');
define('LNG_MBOTS_SOCKS_OK','ОНЛАЙН');
define('LNG_MBOTS_SOCKS_FAILED','ОФФЛАЙН');
define('LNG_MBOTS_PROXY','Прокси');
define('LNG_MBOTS_PROXY_NONE','ID не найден.');
define('LNG_MBOTS_PROXY_SP','IP:Порт');
define('LNG_MBOTS_PROXY_OK','ONLINE');
define('LNG_MBOTS_PROXY_FAILED','OFFLINE');
?>