<?php if(!defined('__INDEX__'))die();
define('LNG_MDBTLOGS_NEW','Новый шаблон');
define('LNG_MDBTLOGS_EDIT','Измение шаблона');
define('LNG_MDBTLOGS_NAME','Название:');
define('LNG_MDBTLOGS_URL','Маска URL:');
define('LNG_MDBTLOGS_PD','POST-данные:');
define('LNG_MDBTLOGS_BEDIT','Сохранить');
define('LNG_MDBTLOGS_BNEW','Добавить');
define('LNG_MDBTLOGS_BBACK','Отмена');
define('LNG_MDBTLOGS_NOTFOUNDED','Шаблон не найден.');
define('LNG_MDBTLOGS_ERROR_1','Шаблон с таким именем уже существует.');
define('LNG_MDBTLOGS_DELQ','Вы действительно хотите удалит этот шаблон?');
define('LNG_MDBTLOGS','Поиск логов по шаблону');
define('LNG_MDBTLOGS_FILTER','Фильтр');
define('LNG_MDBTLOGS_FILTER_TIMES','Период:');
define('LNG_MDBTLOGS_FILTER_CNTS','Страны:');
define('LNG_MDBTLOGS_FILTER_CIDS','CompID\'s:');
define('LNG_MDBTLOGS_FILTER_BNS','Ботнеты:');
define('LNG_MDBTLOGS_FILTER_IPS','IP\'s:');
define('LNG_MDBTLOGS_FILTER_TMP','Шаблон:');
define('LNG_MDBTLOGS_FILTER_TADD','Создать');
define('LNG_MDBTLOGS_FILTER_TDEL','Удалить');
define('LNG_MDBTLOGS_FILTER_TEDIT','Изменить');
define('LNG_MDBTLOGS_FILTER_SEARCH','Найти');
define('LNG_MDBTLOGS_FILTER_RESET','Сброс');
define('LNG_MDBTLOGS_FILTER_MODE','Формат:');
define('LNG_MDBTLOGS_FILTER_MODE1','Нормальный (HTML)');
define('LNG_MDBTLOGS_FILTER_MODE2','Текстовый');
define('LNG_MDBTLOGS_FILTER_MODE3','Вывод в файл');
define('LNG_MDBTLOGS_RESULT','Результат:');
define('LNG_MDBTLOGS_RESULT_NONE','Пусто');
define('LNG_MDBTLOGS_ERROR1','Не удается записать в файл.');
define('LNG_MDBTLOGS_WRITED','Записано %u записей.');
define('LNG_MDBTLOGS_TXT_I1',"CompID: %s\nСтрана: %s\nIP: %s");
?>