<?php if(!defined('__INDEX__'))die();
define('LNG_MBCMDS','Команды');
define('LNG_MBCMDS_NAME','Название:');
define('LNG_MBCMDS_STAT','Статус:');
define('LNG_MBCMDS_STAT_ON','Включен');
define('LNG_MBCMDS_STAT_OFF','Выключен');
define('LNG_MBCMDS_LIMIT','Лимит:');
define('LNG_MBCMDS_CNTS','Страны:');
define('LNG_MBCMDS_CIDS','CompID\'s:');
define('LNG_MBCMDS_BNS','Ботнеты:');
define('LNG_MBCMDS_CMDS','Команды:');
define('LNG_MBCMDS_BACK','Отмена');
define('LNG_MBCMDS_R_CMDS','Команды');
define('LNG_MBCMDS_R_ID','ID');
define('LNG_MBCMDS_R_NAME','Название');
define('LNG_MBCMDS_R_STAT','Статус');
define('LNG_MBCMDS_R_LIMIT','Лимит');
define('LNG_MBCMDS_R_REQ','Отправлено');
define('LNG_MBCMDS_R_EXEC','Выполнено');
define('LNG_MBCMDS_R_CNTS','Страны');
define('LNG_MBCMDS_R_CIDS','CompID\'s');
define('LNG_MBCMDS_R_BNS','Ботнет');
define('LNG_MBCMDS_R_NONE','Пусто');
define('LNG_MBCMDS_R_EDIT','Изменить');
define('LNG_MBCMDS_R_VIEW','Просмотр');
define('LNG_MBCMDS_R_DEL_OK','Удалить');
define('LNG_MBCMDS_R_DEL','Вы действительно хотите удалить команду \'%s\'?');
define('LNG_MBCMDS_R_RES_OK','Сбросить');
define('LNG_MBCMDS_R_RES','Вы действительно хотите сбросить команду \'%s\'?');
define('LNG_MBCMDS_NEWCMD','Добавить команду');
define('LNG_MBCMDS_EDITCMD','Изменить команду');
define('LNG_MBCMDS_VIEWCMD','Просмотр команды');
define('LNG_MBCMDS_EDIT','Изменить');
define('LNG_MBCMDS_ADD','Добавить');
define('LNG_MBCMDS_ERROR_1','Команда не найдена.');
?>