<?php if(!defined('__INDEX__'))die();
define('LNG_MUSERS','Профили');
define('LNG_MUSERS_LIST','Профили');
define('LNG_MUSERS_ID','ID');
define('LNG_MUSERS_LOGIN','Логин');
define('LNG_MUSERS_ADD','Добавить');
define('LNG_MUSERS_VIEW','Просмотр');
define('LNG_MUSERS_EDIT','Изменить');
define('LNG_MUSERS_DEL','Удалить');
define('LNG_MUSERS_DEL_Q','Вы действительно хотите удалить профиль \'%s\'?');
define('LNG_MUSERS_F','Профиль');
define('LNG_MUSERS_F_ADD','Добавить профиль');
define('LNG_MUSERS_F_EDIT','Изменить профиль');
define('LNG_MUSERS_F_VIEW','Просмотр профиля');
define('LNG_MUSERS_F_ADD_OK','Добавить');
define('LNG_MUSERS_F_EDIT_OK','Изменить');
define('LNG_MUSERS_F_BACK','Отмена');
define('LNG_MUSERS_F_LOGIN','Логин:');
define('LNG_MUSERS_F_PASS','Пароль:');
define('LNG_MUSERS_F_PRIV','Права');
define('LNG_MUSERS_F_PRIV_STATS','Статистика');
define('LNG_MUSERS_F_PRIV_STATS_LOGS','Статистика логов');
define('LNG_MUSERS_F_PRIV_STATS_STATS','Статистика троя');
define('LNG_MUSERS_F_PRIV_STATS_RESET','Сброс статистики');
define('LNG_MUSERS_F_PRIV_BOTS','Онлайн-боты');
define('LNG_MUSERS_F_PRIV_BOTS_SOCKS','Просмотр соксов');
define('LNG_MUSERS_F_PRIV_BOTS_PROXY','Просмотр прокси');
define('LNG_MUSERS_F_PRIV_BOTS_LC_SS','Просмотр скриншотов');
define('LNG_MUSERS_F_PRIV_BOTS_CMDS','Команды ботнета');
define('LNG_MUSERS_F_PRIV_BOTS_CMDS_EDIT','Управление командами');
define('LNG_MUSERS_F_PRIV_LOGS_DB','Поиск логов');
define('LNG_MUSERS_F_PRIV_LOGS_DB_EDIT','Удаление логами');
define('LNG_MUSERS_F_PRIV_LOGS_DBT','Поиск логов по шаблону');
define('LNG_MUSERS_F_PRIV_LOGS_DBT_EDIT','Управление шаблонами');
define('LNG_MUSERS_F_PRIV_LOGS_FILES','Обзор скаченых файлов');
define('LNG_MUSERS_F_PRIV_LOGS_FILES_EDIT','Удаление файлов');
define('LNG_MUSERS_F_PRIV_USERS','Профили');
define('LNG_MUSERS_F_PRIV_USERS_EDIT','Управление');
define('LNG_MUSERS_F_PRIV_USER','Профиль');
define('LNG_MUSERS_F_PRIV_OPTIONS','Параметры');
define('LNG_MUSERS_ERROR_1','Пользователь с таким именем уже сущетсвует.');
define('LNG_MUSERS_ERROR_2','Длина пароля должны быть от 6 до 64 символов.');
define('LNG_MUSERS_ERROR_3','Длина логина должны быть от 4 до 10 символов.');
?>