# Project: infected
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = infected_private.res
OBJ  = infected.o zipstore.o $(RES)
LINKOBJ  = infected.o zipstore.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = infected.exe
CXXFLAGS = $(CXXINCS)   -O3
CFLAGS = $(INCS)   -O3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before infected.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "infected.exe" $(LIBS)

infected.o: infected.c
	$(CC) -c infected.c -o infected.o $(CFLAGS)

zipstore.o: zipstore.c
	$(CC) -c zipstore.c -o zipstore.o $(CFLAGS)

infected_private.res: infected_private.rc 
	$(WINDRES) -i infected_private.rc --input-format=rc -o infected_private.res -O coff 
