<?php if(!defined('__INDEX__'))die();
define('LNG_MBCMDS','Remote commands');
define('LNG_MBCMDS_NAME','Name:');
define('LNG_MBCMDS_STAT','Status:');
define('LNG_MBCMDS_STAT_ON','Enabled');
define('LNG_MBCMDS_STAT_OFF','Disabled');
define('LNG_MBCMDS_LIMIT','Limit:');
define('LNG_MBCMDS_CNTS','Countries:');
define('LNG_MBCMDS_CIDS','CompID\'s:');
define('LNG_MBCMDS_BNS','Botnets:');
define('LNG_MBCMDS_CMDS','Commands:');
define('LNG_MBCMDS_BACK','Cancel');
define('LNG_MBCMDS_R_CMDS','Groups of commands');
define('LNG_MBCMDS_R_ID','ID');
define('LNG_MBCMDS_R_NAME','Name');
define('LNG_MBCMDS_R_STAT','Status');
define('LNG_MBCMDS_R_LIMIT','Limit');
define('LNG_MBCMDS_R_REQ','Sended');
define('LNG_MBCMDS_R_EXEC','Executed');
define('LNG_MBCMDS_R_CNTS','Countries');
define('LNG_MBCMDS_R_CIDS','CompID\'s');
define('LNG_MBCMDS_R_BNS','Botnets');
define('LNG_MBCMDS_R_NONE','Empty');
define('LNG_MBCMDS_R_EDIT','Edit');
define('LNG_MBCMDS_R_VIEW','View');
define('LNG_MBCMDS_R_DEL_OK','Delete');
define('LNG_MBCMDS_R_DEL','You really want delete group of commands \'%s\'?');
define('LNG_MBCMDS_R_RES_OK','Reset');
define('LNG_MBCMDS_R_RES','You really want reset group of commands  \'%s\'?');
define('LNG_MBCMDS_NEWCMD','New group');
define('LNG_MBCMDS_EDITCMD','Edit group');
define('LNG_MBCMDS_VIEWCMD','View group');
define('LNG_MBCMDS_EDIT','Save');
define('LNG_MBCMDS_ADD','Add');
define('LNG_MBCMDS_ERROR_1','Group not founded.');
?>