<?php if(!defined('__INDEX__'))die();
define('LNG_MBOTS','Bots');
define('LNG_MBOTS_FILTER','Filter');
define('LNG_MBOTS_FILTER_CIDS','CompID\'s:');
define('LNG_MBOTS_FILTER_BNS','Botnets:');
define('LNG_MBOTS_FILTER_CNTS','Countries:');
define('LNG_MBOTS_FILTER_IPS','IP\'s:');
define('LNG_MBOTS_FILTER_TYPE','Type:');
define('LNG_MBOTS_FILTER_TYPE1','Outside NAT');
define('LNG_MBOTS_FILTER_TYPE2','Inside NAT');
define('LNG_MBOTS_FILTER_TYPE3','Any');
define('LNG_MBOTS_FILTER_APPLY','Apply');
define('LNG_MBOTS_RESULT','Result:');
define('LNG_MBOTS_RESULT_NONE','Empty');
define('LNG_MBOTS_RESULT_CID','CompID');
define('LNG_MBOTS_RESULT_VERBID','Ver/Botnet');
define('LNG_MBOTS_RESULT_IP','IP');
define('LNG_MBOTS_RESULT_CNT','Country');
define('LNG_MBOTS_RESULT_SOCKS','Socks');
define('LNG_MBOTS_RESULT_PROXY','Proxy');
define('LNG_MBOTS_RESULT_ONLINE','Online&nbsp;time');
define('LNG_MBOTS_RESULT_LAG','Lag');
define('LNG_MBOTS_RESULT_HIDEIP','Hide');
define('LNG_MBOTS_RESULT_LS_SS','Screenshot');
define('LNG_MBOTS_RESULT_LS_KOS','Kill&nbsp;OS');
define('LNG_MBOTS_RESULT_TIME','Time&nbsp;of&nbsp;report');
define('LNG_MBOTS_RESULT_FTIME','Time&nbsp;of&nbsp;first&nbsp;report');
define('LNG_MBOTS_RESULT_STATUS','Status:');
define('LNG_MBOTS_RESULT_STATUS_1','Not Used');
define('LNG_MBOTS_RESULT_STATUS_2','Used');
define('LNG_MBOTS_RESULT_STATUS_3','Mark as used');
define('LNG_MBOTS_RESULT_STATUS_4','Mark as not used');
define('LNG_MBOTS_RESULT_STATUS_KOS_OK','KILLED');
define('LNG_MBOTS_RESULT_STATUS_KOS_FL','ERROR');
define('LNG_MBOTS_LS_SS_VIEW','View');
define('LNG_MBOTS_LS_KOS_VIEW','Kill');
define('LNG_MBOTS_RESULT_PREV','<< Back');
define('LNG_MBOTS_RESULT_NEXT','Forward >>');
define('LNG_MBOTS_SS','Screenshoot');
define('LNG_MBOTS_KOS','Kill OS');
define('LNG_MBOTS_LS_NONE','CompID not founded.');
define('LNG_MBOTS_SOCKS','Socks');
define('LNG_MBOTS_SOCKS_NONE','ID not founded.');
define('LNG_MBOTS_SOCKS_SP','IP:Port');
define('LNG_MBOTS_SOCKS_OK','ONLINE');
define('LNG_MBOTS_SOCKS_FAILED','OFFLINE');
define('LNG_MBOTS_PROXY','Proxy');
define('LNG_MBOTS_PROXY_NONE','ID not founded.');
define('LNG_MBOTS_PROXY_SP','IP:Port');
define('LNG_MBOTS_PROXY_OK','ONLINE');
define('LNG_MBOTS_PROXY_FAILED','OFFLINE');
?>