<?if(!defined('__INDEX__'))die();
define('LNG_MDBLOGS',                  'Logs search');
define('LNG_MDBLOGS_FILTER',           'Search filter');
define('LNG_MDBLOGS_FILTER_DATES',     'From date (dd.mm) %s to date %s');
define('LNG_MDBLOGS_FILTER_COUNTRIES', 'Countries:');
define('LNG_MDBLOGS_FILTER_COMPIDS',   'CompID\'s:');
define('LNG_MDBLOGS_FILTER_BOTNETS',   'Botnets:');
define('LNG_MDBLOGS_FILTER_IPS',       'IP\'s:');
define('LNG_MDBLOGS_FILTER_CONT',      'Query:');
define('LNG_MDBLOGS_FILTER_TYPE',      'Log type:');
define('LNG_MDBLOGS_FILTER_TYPE_L',    'Any|HTTP|HTTPS|HTTP/HTTPS|FTP|POP3|Grabbed data|Protected Storage|IE history|Other');
define('LNG_MDBLOGS_FILTER_CS',        'Case sensitive');
define('LNG_MDBLOGS_FILTER_UD',        'Exclude retries of contents (slow)');
define('LNG_MDBLOGS_FILTER_NC',        'Don\'t show computer names');
define('LNG_MDBLOGS_FILTER_SEARCH',    'Search');
define('LNG_MDBLOGS_FILTER_RESET',     'Reset');
define('LNG_MDBLOGS_FILTER_DELETE',    'Delete');
define('LNG_MDBLOGS_FILTER_MODE',      'Output:');
define('LNG_MDBLOGS_FILTER_MODES',     'Normal|Text|File');
define('LNG_MDBLOGS_TXT_N1',           'New OS:');
define('LNG_MDBLOGS_TXT_N2',           'New version / botnet:');
define('LNG_MDBLOGS_TXT_N3',           'New IP:');
define('LNG_MDBLOGS_VIEW',             'View log');
define('LNG_MDBLOGS_VIEW_NONE',        'Log not exists.');
define('LNG_MDBLOGS_DELETE1',          'You really want deleted logs using this search filter?');
define('LNG_MDBLOGS_DELETE2',          'Are you sure?');
define('LNG_MDBLOGS_DELETE_R',         'Deleted %u logs.');
define('LNG_MDBLOGS_RESULT',           'Result:');
define('LNG_MDBLOGS_RESULT_NONE',      'Empty');
define('LNG_MDBLOGS_RESULT_DBNONE',    'Databases for this period not founded.');
define('LNG_MDBLOGS_LOG_CID',          'CompID / IP / Country:');
define('LNG_MDBLOGS_LOG_TIME',         'Report (this / first / last):');
define('LNG_MDBLOGS_LOG_VERBN',        'Version / Botnet:');
define('LNG_MDBLOGS_LOG_STIME',        'System time / Up time:');
define('LNG_MDBLOGS_LOG_WVER',         'OS version:');
define('LNG_MDBLOGS_LOG_WVERD',        '%u.%u, build %u, service pack %u, language %u');
define('LNG_MDBLOGS_LOG_PROC',         'Process:');
define('LNG_MDBLOGS_ERROR1',           'Failed write to file.');
define('LNG_MDBLOGS_WRITED',           'Writed %u logs.');
define('LNG_MDBLOGS_MENU1',            'All logs for this date in text mode');
define('LNG_MDBLOGS_MENU2',            'All logs for this date in HTML mode');
?>