<?php if(!defined('__INDEX__'))die();
define('LNG_MDBTLOGS_NEW','New template');
define('LNG_MDBTLOGS_EDIT','Edit template');
define('LNG_MDBTLOGS_NAME','Name:');
define('LNG_MDBTLOGS_URL','URL mask:');
define('LNG_MDBTLOGS_PD','POST-data:');
define('LNG_MDBTLOGS_BEDIT','Save');
define('LNG_MDBTLOGS_BNEW','Add');
define('LNG_MDBTLOGS_BBACK','Cancel');
define('LNG_MDBTLOGS_NOTFOUNDED','Template not founded.');
define('LNG_MDBTLOGS_ERROR_1','Template with this name already exists.');
define('LNG_MDBTLOGS_DELQ','You really want delete template?');
define('LNG_MDBTLOGS','Logs search with template');
define('LNG_MDBTLOGS_FILTER','Filter');
define('LNG_MDBTLOGS_FILTER_TIMES','Dates:');
define('LNG_MDBTLOGS_FILTER_CNTS','Countries:');
define('LNG_MDBTLOGS_FILTER_CIDS','CompID\'s:');
define('LNG_MDBTLOGS_FILTER_BNS','Botnets:');
define('LNG_MDBTLOGS_FILTER_IPS','IP\'s:');
define('LNG_MDBTLOGS_FILTER_TMP','Template:');
define('LNG_MDBTLOGS_FILTER_TADD','New');
define('LNG_MDBTLOGS_FILTER_TDEL','Delete');
define('LNG_MDBTLOGS_FILTER_TEDIT','Edit');
define('LNG_MDBTLOGS_FILTER_SEARCH','Search');
define('LNG_MDBTLOGS_FILTER_RESET','Reset');
define('LNG_MDBTLOGS_FILTER_DELETE','Delete');
define('LNG_MDBTLOGS_FILTER_MODE','Output:');
define('LNG_MDBTLOGS_FILTER_MODE1','Normal');
define('LNG_MDBTLOGS_FILTER_MODE2','Text');
define('LNG_MDBTLOGS_FILTER_MODE3','File');
define('LNG_MDBTLOGS_RESULT','Result:');
define('LNG_MDBTLOGS_RESULT_NONE','Empty');
define('LNG_MDBTLOGS_ERROR1','Failed write to file.');
define('LNG_MDBTLOGS_WRITED','Writed %u logs.');
define('LNG_MDBTLOGS_TXT_I1',"CompID: %s\nCountry: %s\nIP: %s");
?>