<?php if(!defined('__INDEX__'))die();
define('LNG_MUSERS','Profiles');
define('LNG_MUSERS_LIST','Profiles');
define('LNG_MUSERS_ID','ID');
define('LNG_MUSERS_LOGIN','Login');
define('LNG_MUSERS_ADD','Add');
define('LNG_MUSERS_VIEW','View');
define('LNG_MUSERS_EDIT','Edit');
define('LNG_MUSERS_DEL','Delete');
define('LNG_MUSERS_DEL_Q','You really want delete profile \'%s\'?');
define('LNG_MUSERS_F','Profile');
define('LNG_MUSERS_F_ADD','Add profile');
define('LNG_MUSERS_F_EDIT','Edit profile');
define('LNG_MUSERS_F_VIEW','View profile');
define('LNG_MUSERS_F_ADD_OK','Add');
define('LNG_MUSERS_F_EDIT_OK','Edit');
define('LNG_MUSERS_F_BACK','Cancel');
define('LNG_MUSERS_F_LOGIN','Login:');
define('LNG_MUSERS_F_PASS','Password:');
define('LNG_MUSERS_F_PRIV','Rights');
define('LNG_MUSERS_F_PRIV_STATS','Statistics');
define('LNG_MUSERS_F_PRIV_STATS_LOGS','Logs statistics');
define('LNG_MUSERS_F_PRIV_STATS_STATS','Global statistics');
define('LNG_MUSERS_F_PRIV_STATS_RESET','Reset');
define('LNG_MUSERS_F_PRIV_BOTS','Online bots');
define('LNG_MUSERS_F_PRIV_BOTS_SOCKS','View socks');
define('LNG_MUSERS_F_PRIV_BOTS_PROXY','View proxy');
define('LNG_MUSERS_F_PRIV_BOTS_LC_SS','View screenshots');
define('LNG_MUSERS_F_PRIV_BOTS_CMDS','Remote commands');
define('LNG_MUSERS_F_PRIV_BOTS_CMDS_EDIT','Edit');
define('LNG_MUSERS_F_PRIV_LOGS_DB','Search logs');
define('LNG_MUSERS_F_PRIV_LOGS_DB_EDIT','Delete');
define('LNG_MUSERS_F_PRIV_LOGS_DBT','Search logs with templates');
define('LNG_MUSERS_F_PRIV_LOGS_DBT_EDIT','Edit');
define('LNG_MUSERS_F_PRIV_LOGS_FILES','Browse uploaded files');
define('LNG_MUSERS_F_PRIV_LOGS_FILES_EDIT','Deleting files');
define('LNG_MUSERS_F_PRIV_USERS','Profiles');
define('LNG_MUSERS_F_PRIV_USERS_EDIT','Edit');
define('LNG_MUSERS_F_PRIV_USER','Profile');
define('LNG_MUSERS_F_PRIV_OPTIONS','Options');
define('LNG_MUSERS_ERROR_1','Profile with this login already exists.');
define('LNG_MUSERS_ERROR_2','Password must contain 6-64 characters.');
define('LNG_MUSERS_ERROR_3','Login must contain 6-64 characters.');
?>