<?if(!defined('__INDEX__'))die();
define('LNG_MDBLOGS',                  'Поиск логов');
define('LNG_MDBLOGS_FILTER',           'Фильтр поиска');
define('LNG_MDBLOGS_FILTER_DATES',     'С даты (дд.мм) %s по дату %s');
define('LNG_MDBLOGS_FILTER_COUNTRIES', 'Страны:');
define('LNG_MDBLOGS_FILTER_COMPIDS',   'CompID\'s:');
define('LNG_MDBLOGS_FILTER_BOTNETS',   'Ботнеты:');
define('LNG_MDBLOGS_FILTER_IPS',       'IP\'s:');
define('LNG_MDBLOGS_FILTER_CONT',      'Содержимое:');
define('LNG_MDBLOGS_FILTER_TYPE',      'Тип:');
define('LNG_MDBLOGS_FILTER_TYPE_L',    'Любой|HTTP|HTTPS|HTTP/HTTPS|FTP|POP3|Grabbed data|Protected Storage|IE history|Другое');
define('LNG_MDBLOGS_FILTER_CS',        'С учетом регистра (ускоряет поиск)');
define('LNG_MDBLOGS_FILTER_UD',        'Исключать повтор содержимого (замедляет поиск)');
define('LNG_MDBLOGS_FILTER_NC',        'Не отображать данные о компьютере');
define('LNG_MDBLOGS_FILTER_SEARCH',    'Найти');
define('LNG_MDBLOGS_FILTER_RESET',     'Сброс');
define('LNG_MDBLOGS_FILTER_DELETE',    'Удалить');
define('LNG_MDBLOGS_FILTER_MODE',      'Формат:');
define('LNG_MDBLOGS_FILTER_MODES',     'Нормальный (HTML)|Текстовый|Вывод в файл');
define('LNG_MDBLOGS_TXT_N1',           'Новая OS:');
define('LNG_MDBLOGS_TXT_N2',           'Новая версия / ботнет:');
define('LNG_MDBLOGS_TXT_N3',           'Смена IP:');
define('LNG_MDBLOGS_VIEW',             'Просмотр лога');
define('LNG_MDBLOGS_VIEW_NONE',        'Лог не найден.');
define('LNG_MDBLOGS_DELETE1',          'Вы действительно хотите удалить логи по заданной маске?');
define('LNG_MDBLOGS_DELETE2',          'Вы уверены?');
define('LNG_MDBLOGS_DELETE_R',         'Удалено %u записей.');
define('LNG_MDBLOGS_RESULT',           'Результат:');
define('LNG_MDBLOGS_RESULT_NONE',      'Пусто');
define('LNG_MDBLOGS_RESULT_DBNONE',    'Не найдены базы данных для указанного периуда.');
define('LNG_MDBLOGS_LOG_CID',          'CompID / IP / Страна:');
define('LNG_MDBLOGS_LOG_TIME',         'Отчет (лог / первый / последний):');
define('LNG_MDBLOGS_LOG_VERBN',        'Версия / Ботнет:');
define('LNG_MDBLOGS_LOG_STIME',        'Системное время / Время логина:');
define('LNG_MDBLOGS_LOG_WVER',         'Версия OS:');
define('LNG_MDBLOGS_LOG_WVERD',        '%u.%u, сборка %u, сервис пак %u, язык %u');
define('LNG_MDBLOGS_LOG_PROC',         'Процесс:');
define('LNG_MDBLOGS_ERROR1',           'Не удается записать в файл.');
define('LNG_MDBLOGS_WRITED',           'Сохранено %u записей.');
define('LNG_MDBLOGS_MENU1',            'Все логи за эту дату в текстовом режиме');
define('LNG_MDBLOGS_MENU2',            'Все логи за эту дату в HTML режиме');
?>