/* CryptErr.cpp --

   This file is part of the "yoda's Protector".

   Copyright (C) 2004-2005 Ashkbiz Danehkar
   Copyright (C) 2000-2001 yoda/FReAK2FReAK
   All Rights Reserved.

   yoda's Protector library are free software; you can redistribute them
   and/or modify them under the terms of the GNU General Public License as
   published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; see the file COPYRIGHT.TXT.
   If not, write to the Free Software Foundation, Inc.,
   59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

   Ashkbiz Danehkar
   <ashkbiz@yahoo.com>
*/
#include "stdafx.h"
#include "LangData.h"

DWORD dwLanguageID		= LANG_ENGLISH;
//----- CONST ----
// all opcodes are in reverse order
sViewLang ViewLangPERTable[ViewLangNum]=
{
	//-----LANG_ENGLISH-----
	{
	"File",
	"Open",
	"Save as...",
	"Protect",
	"Exit",
	"Option",
	"Protection",
	"View",
	"Interface Language",
	"Help",
	"Help contents\tF1",
	"About...",
	"Protect",
	"File to Protect",
	"Output to FileName",
	"Protect",
	"Test",
	"Options",
	"Protection",
	"Anti-SoftICE Protection",
	"Checksum Protection",
	"API Redirection",
	"Anti-Dump Protection",
	"Clear Import Information",
	"Clear PE header",
	"Compress Option",
	"Advanced",
	"Remove .reloc section",
	"Remove debug information",
	"Eliminate MS-DOS header",
	"Optimize MS-DOS header",
	"Other",
	"Create backup copy (BAK-file)",
	"Auto run after loading",
	"Exit when done",
	"Section's Name"	
	},
	//-----LANG_GERMAN-----
	{
	"Datei",
	"Öffnen",
	"Bewahren als...",
	"Schützen",
	"Beenden",
	"Auserlesen",
	"Schutz",
	"Ansicht",
	"Sprache",
	"Hilfe",
	"Hilfethemen\tF1",
	"Über das Yoda Protector...",
	"Schützen",
	"Öffnen datei",
	"Bewahren als...",
	"Schützen",
	"Prüfung",
	"Auserlesen",
	"Schutz",
	"Anti-SoftICE Schutz",
	"Schecksumme Schutz",
	"API Umleitung",
	"Anti-Dump Schutz",
	"Klare Import-Informationen",
	"Löschen PE header",
	"Kompresse Rate",
	"Anspruchsvolle",
	"Entfernen .reloc teiles",
	"Entfernen debuggen-Informationen",
	"Schließen MS-DOS header",
	"Optimieren MS-DOS header",
	"Andere",
	"Sicherungskopie (BAK-Datei)",
	"Starten wenn geöffnet",
	"Ausgang wenn gemacht",
	"Der Name Teiles"
	},
	//-----LANG_FRENCH-----
	{
	"Fichier",
	"Ouvert",
	"Sauvez comme...",
	"Protégez",
	"Quitter",
	"Choisi",
	"Protection",
	"Affichage",
	"Langue",
	"Aide",
	"Rubriques d'aide\tF1",
	"A porpose d'Yoda Protector...",
	"Protégez",
	"Ouvert fichier",
	"Sauvez comme...",
	"Protégez",
	"L'épreuve",
	"Choisi",
	"Protection",
	"La Protection Anti-SoftICE ",
	"La Protection du chèque-somme",
	"Le Réacheminement de l'API",
	"La Protection de l'Anti-Dump",
	"Effacez importent de l'information",
	"Effacez L'en-tête PE",
	"Taux de Compression",
	"Avancées",
	"Enlevez la section du .reloc",
	"Enlevez le debug-information",
	"Éliminez l'en-tête du MS-DOS",
	"Optimisez l'en-tête du MS-DOS",
	"Autres",
	"Créez la copie auxiliaire (BAK-fichier)",
	"La course quand a ouvert",
	"Quitter quand fait",
	"Le Nom de section "
	},
	//-----LANG_ITALIAN-----
	{
	"Archivio",
	"Apri",
	"Salva come...",
	"Proteggi",
	"Fine",
	"Opzioni",
	"Protezione",
	"Mostra",
	"Lingua",
	"Aiuto",
	"Aiuto\tF1",
	"Informazioni su Yoda Protector...",
	"Proteggi",
	"Apri archivio",
	"Salva come...",
	"Proteggi",
	"Test",
	"Opzioni",
	"Protezione",
	"Protezione AntiSoftICE",
	"Controllo Protezione",
	"Reinstradi funzione di API",
	"Protezione Anti-Dump",
	"Annulli informazioni di importazione",
	"Annulla testata PE",
	"Modalità di compressione",
	"Avanzati",
	"Rimuova sezione del .reloc",
	"Rimuovi informazioni debug ",
	"Elimini testata di MS-DOS",
	"Ottimizzi testata di MS-DOS",
	"Altri",
	"Crei copia di riserva (BAK-archivio)",
	"Avvia quando ha finito",
	"Chiudi quando ha finito",
	"Il Nome di sezione"
	},
	//-----LANG_SPANISH-----
	{
	"Archivo",
	"Abra",
	"Ahorre como...",
	"Proteja",
	"Salir",
	"Opción",
	"Protección",
	"Ver",
	"Idioma",
	"Ayuda",
	"Temas de Ayuda\tF1",
	"Acerca de Yoda Protector...",
	"Proteja",
	"Abra archivo",
	"Ahorre como...",
	"Proteja",
	"Examen",
	"Opción",
	"Protección",
	"Protección de Anti-SoftICE",
	"Protección del cheque-suma",
	"Redirection de API",
	"Protección del Anti-Dump",
	"Anule información de importación",
	"Anule título de PE",
	"Proporción de Condensación",
	"Avanzados",
	"Quite sección del .reloc",
	"Quite el debug-información",
	"Elimine título de MS-DOS",
	"Perfeccione título de MS-DOS",
	"Otros",
	"Copie backup (BAK-archivo)",
	"Corra cuando está cargado",
	"Salida cuando se hace",
	"El Nombre de sección"
	},
	//-----LANG_ENGLISH-----
	{
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                "
	}
};